// Earlier Selected Works / Research Archive.
// Content is limited to information supplied in the 13-project expansion brief.

export const archiveProjects = [
  {
    id: "machine-learning-kerf-bending",
    number: "06",
    slug: "machine-learning-kerf-bending",
    title: "Machine Learning for Kerf-Bending",
    subtitle: "Predicting timber curvature from parametric kerf geometry",
    year: "IAAC Summer 2022",
    type: "Academic Work",
    projectType: "Seminar Project",
    classification: "Academic",
    institution: "IAAC",
    programme: "MaCAD",
    faculty: "Gabriella Rossi",
    assistants: ["Hesham Shawqy"],
    collaborators: ["Naitik Sharma", "Mahmoud Ramdane", "Olga Poletkina"],
    role: null,
    location: null,
    keywords: ["Kerf Bending", "Parametric Dataset", "Machine Learning", "Regression", "Grasshopper / Hops"],
    tags: ["Research", "Fabrication", "Machine Learning", "Parametric"],
    indexFocus: "Machine Learning / Material Bending",
    shortDescription: "A parametric and machine-learning workflow for predicting the curvature of kerf-bent timber sheets.",
    introduction: [
      "Kerf bending reduces local timber-sheet stiffness by removing material where deformation is required. This project studies the reciprocal relationship between kerf geometry and the curvature that results from bending.",
      "A parametric Grasshopper system generated kerf-pattern datasets, while regression models predicted bending radius and returned those predictions to the geometric workflow. Machine learning operates inside a computational-material feedback loop rather than after the design process.",
    ],
    externalLinks: [],
    mediaFolder: "/projects/machine-learning-kerf-bending",
    thumbnail: null,
    thumbnailType: "image",
    thumbnailAlt: "Kerf-bent timber and machine-learning prediction study",
    heroMedia: null,
    heroMediaType: "image",
    heroAlt: "Kerf-bending geometry and timber curvature",
    featured: false,
    archive: true,
    placeholder: false,
    visualVariant: "field",
    content: [
      { type: "researchQuestion", text: "Can we predict the final curvature of a kerf-bent timber sheet from the geometry of its kerf pattern?" },
      { type: "sectionTitle", number: "01", title: "Problem / Material Behaviour" },
      { type: "text", heading: "Removing material to enable curvature", paragraphs: ["Repeated kerf cuts reduce local stiffness so that a relatively rigid timber sheet can form curved configurations. Kerf depth, tooth width, spacing, rotation, timber thickness and pattern geometry operate simultaneously and alter the final bending radius."] },
      { type: "mediaGroup", groups: ["material", "overview"], fallbackGroups: ["process"], layout: "asymmetric", label: "KERF BENDING PRINCIPLE", placeholderCount: 3 },
      { type: "sectionTitle", number: "02", title: "Geometrical Simulation" },
      { type: "text", heading: "A geometric parameter space", paragraphs: ["Rather than relying only on a conventional physics simulation, the Grasshopper system parametrically describes a bent sheet through variables controlling wood thickness, teeth width and depth, distance between teeth, rotation angle, kerf-related angular conditions and resulting radius."] },
      { type: "dataGrid", label: "Geometric parameters", items: ["Wood thickness", "Teeth width", "Teeth depth", "Distance between teeth", "Rotation angle", "Kerf angular conditions", "Resulting radius"] },
      { type: "mediaGroup", groups: ["geometry", "grasshopper"], fallbackGroups: ["diagram"], layout: "full", label: "GRASSHOPPER GEOMETRY", placeholderCount: 1 },
      { type: "sectionTitle", number: "03", title: "Dataset Generation" },
      { type: "text", heading: "Four iterative datasets", paragraphs: ["Four dataset versions were developed, with each iteration responding to shortcomings in the previous one. Within this experiment, a parameter range of approximately 0-200 mm provided the most useful range for accurate prediction; it is not presented as a universal material rule."] },
      { type: "dataGrid", label: "Dataset finding", items: [{ label: "Versions", value: "4" }, { label: "Useful tested range", value: "Approx. 0-200 mm" }] },
      { type: "mediaGroup", groups: ["dataset"], fallbackGroups: ["analysis"], layout: "gallery", label: "DATASET ITERATIONS", placeholderCount: 4 },
      { type: "sectionTitle", number: "04", title: "Understanding the Parameter Space" },
      { type: "flow", label: "Predictive relationship", steps: ["Input parameters", "Parametric geometry", "Bending behaviour", "Resulting radius"] },
      { type: "mediaGroup", groups: ["parameter"], fallbackGroups: ["workflow"], layout: "full", label: "PARAMETER SPACE", placeholderCount: 1 },
      { type: "sectionTitle", number: "05", title: "Feature Exploration" },
      { type: "text", heading: "Analysing before training", paragraphs: ["Pairplots, dimensionality reduction, correlation heatmaps and Principal Component Analysis were used to examine relationships between features and the target variable. These charts document analytical decisions rather than decorative data-science imagery."] },
      { type: "dataGrid", label: "Analytical methods", items: ["Pairplots", "Dimensionality reduction", "Correlation heatmap", "Principal Component Analysis"] },
      { type: "mediaGroup", groups: ["analysis", "feature"], fallbackGroups: ["diagram"], layout: "gallery", label: "FEATURE EXPLORATION", placeholderCount: 4 },
      { type: "sectionTitle", number: "06", title: "Regression Models" },
      { type: "text", heading: "Comparing shallow-learning methods", paragraphs: ["Linear Regression, Kernel Ridge, XGB Regressor and Polynomial Regression were compared. Polynomial degrees 2, 3 and 4 were tested, with degree 4 producing the strongest result among the documented polynomial models."] },
      { type: "dataGrid", label: "Regression comparison", items: ["Linear Regression", "Kernel Ridge", "XGB Regressor", "Polynomial Regression", { label: "Strongest polynomial", value: "Degree 4" }] },
      { type: "mediaGroup", groups: ["regression"], fallbackGroups: ["analysis"], layout: "gallery", label: "REGRESSION MODELS", placeholderCount: 4 },
      { type: "sectionTitle", number: "07", title: "Artificial Neural Network" },
      { type: "text", heading: "A controlled ANN comparison", paragraphs: ["Different ANN regression architectures were tested. A model with approximately 224 parameters and linear activation was identified as one of the stronger configurations with comparatively low MSE loss; it is presented as a controlled comparison, not a deep-learning breakthrough."] },
      { type: "dataGrid", label: "Documented ANN", items: [{ label: "Parameters", value: "Approx. 224" }, { label: "Activation", value: "Linear" }, { label: "Evaluation", value: "MSE loss" }] },
      { type: "mediaGroup", groups: ["ann"], fallbackGroups: ["analysis"], layout: "gallery", label: "ANN COMPARISON", placeholderCount: 3 },
      { type: "sectionTitle", number: "08", title: "ANN vs Shallow Learning" },
      { type: "text", heading: "From numerical loss to geometry", paragraphs: ["The best-performing ANN and shallow-learning models were compared not only numerically but through their geometric predictions. This comparison established the need to bring trained models back into Grasshopper."] },
      { type: "mediaGroup", groups: ["comparison"], fallbackGroups: ["analysis"], layout: "two-column", label: "ANN / SHALLOW LEARNING", placeholderCount: 2 },
      { type: "sectionTitle", number: "09", title: "Hops + Live ML Connection" },
      { type: "flow", label: "Live connection", steps: ["Grasshopper", "Hops", "Google Colab", "Ngrok", "TensorFlow / .h5 model", "Prediction", "Grasshopper geometry"] },
      { type: "text", heading: "Predictions returned to the model", paragraphs: ["Google Colab provided cloud computation and Ngrok enabled communication with the trained model. Predictions could therefore be visualised geometrically inside Grasshopper."] },
      { type: "mediaGroup", groups: ["hops", "prediction", "animation"], fallbackGroups: ["workflow", "gifs"], layout: "asymmetric", label: "LIVE ML / GIF", placeholderCount: 3 },
      { type: "sectionTitle", number: "10", title: "150-Sample Comparison" },
      { type: "text", heading: "Testing approximately 150 iterations", paragraphs: ["Deviations between predicted and generated geometry were recorded over approximately 150 Grasshopper iterations. In this test, the shallow-learning workflow produced a smaller deviation range than the ANN; no additional accuracy percentage is inferred."] },
      { type: "dataGrid", label: "Documented comparison", items: [{ label: "Iterations", value: "Approx. 150" }, { label: "Smaller deviation range", value: "Shallow-learning regression" }] },
      { type: "mediaGroup", groups: ["result"], fallbackGroups: ["analysis"], layout: "gallery", label: "PREDICTION COMPARISON", placeholderCount: 3 },
      { type: "sectionTitle", number: "11", title: "Conclusion" },
      { type: "flow", label: "Material-computational loop", steps: ["Parametric kerf pattern", "Dataset", "Regression", "Predicted curvature", "Live Grasshopper feedback"] },
    ],
  },
  {
    id: "post-digital-temples",
    number: "07",
    slug: "post-digital-temples",
    title: "Post Digital Temples",
    subtitle: "Architectural morphology through parametric datasets and 3D GANs",
    year: "IAAC Summer 2022",
    type: "Academic Work",
    projectType: "Seminar Project",
    classification: "Academic",
    institution: "IAAC",
    programme: "MaCAD",
    faculty: "Oana Taut",
    assistants: ["Aleksander Mastalski"],
    collaborators: ["Naitik Sharma", "Mahmoud Ramdane", "Daniyal Tariq"],
    role: null,
    location: null,
    keywords: ["Indian Temple Morphology", "Parametric Dataset", "Voxelisation", "3D GAN", "Generative Research"],
    tags: ["Research", "Generative AI", "Parametric", "Machine Learning"],
    indexFocus: "Generative AI / Architectural Morphology",
    shortDescription: "A design-research experiment encoding Indian temple-spire morphology into synthetic voxel datasets for 3D GAN training.",
    introduction: ["Post Digital Temples investigates whether recurrent geometric characteristics of Indian temple spires can be encoded parametrically and learned through a three-dimensional generative model.", "The study analyses two broad temple traditions, generates controlled synthetic datasets, voxelises the forms and uses GAN experiments to test what morphological characteristics can be learned and recombined."],
    externalLinks: [],
    mediaFolder: "/projects/post-digital-temples",
    thumbnail: null,
    thumbnailType: "image",
    thumbnailAlt: "Parametric Indian temple-spire dataset and generated forms",
    heroMedia: null,
    heroMediaType: "image",
    heroAlt: "Post Digital Temples generated architectural morphology",
    featured: false,
    archive: true,
    placeholder: false,
    visualVariant: "topology",
    content: [
      { type: "sectionTitle", number: "01", title: "Understanding Temple Styles" },
      { type: "typologyGrid", items: [{ number: "01", title: "North Indian", description: "A more curvilinear vertical spire associated with the Shikhara tradition." }, { number: "02", title: "South Indian", description: "A more strongly stepped or pyramidal spire associated with the Vimana tradition." }] },
      { type: "text", heading: "A geometric rather than exhaustive cultural study", paragraphs: ["The computational focus is limited to recurrent three-dimensional characteristics of temple spires. It does not claim to reproduce every historical or cultural dimension of temple architecture."] },
      { type: "mediaGroup", groups: ["typology", "precedent"], fallbackGroups: ["overview"], layout: "two-column", label: "TEMPLE STYLES", placeholderCount: 2 },
      { type: "sectionTitle", number: "02", title: "Parametricism in Indian Temples" },
      { type: "text", heading: "Encoding recurrent geometric features", paragraphs: ["Cascading geometries, recursive subdivision, geometrical fractality, repeated spire elements, radial organisation, varying taper and sliced surfaces were translated into parametric rules. Loops controlled repetition and subdivision, while slicing approximated ornamental articulation."] },
      { type: "dataGrid", label: "Geometric features", items: ["Cascading geometries", "Recursive subdivision", "Geometrical fractality", "Repeated spires", "Radial organisation", "Varying taper", "Sliced surfaces"] },
      { type: "mediaGroup", groups: ["parametric"], fallbackGroups: ["diagram"], layout: "asymmetric", label: "PARAMETRIC MORPHOLOGY", placeholderCount: 3 },
      { type: "sectionTitle", number: "03", title: "Synthetic Dataset" },
      { type: "flow", label: "Dataset generation", steps: ["Temple precedent", "Geometric feature", "Parametric rule", "Iterations", "Synthetic dataset"] },
      { type: "text", heading: "Controlled generated samples", paragraphs: ["Generative Grasshopper definitions produced multiple spire variations while controlling their geometric features, creating sufficient samples for machine-learning experiments without relying only on scanned monuments."] },
      { type: "mediaGroup", groups: ["dataset"], fallbackGroups: ["process"], layout: "gallery", label: "SYNTHETIC DATASET", placeholderCount: 4 },
      { type: "sectionTitle", number: "04", title: "Generative Adversarial Networks" },
      { type: "text", heading: "Generator and discriminator", paragraphs: ["The documented iWGAN / Wasserstein GAN uses a generator to produce samples resembling the dataset and a discriminator to distinguish generated samples from training examples. Their repeated competition supports learning, but the architectural experiment remains the focus."] },
      { type: "dataGrid", label: "GAN roles", items: [{ label: "Generator", value: "Produces candidate samples" }, { label: "Discriminator", value: "Distinguishes generated and training samples" }] },
      { type: "mediaGroup", groups: ["gan"], fallbackGroups: ["workflow"], layout: "full", label: "GAN WORKFLOW", placeholderCount: 1 },
      { type: "sectionTitle", number: "05", title: "3D GAN + Voxelisation" },
      { type: "text", heading: "Consistent volumetric representation", paragraphs: ["Temple geometries were voxelised into approximately 64 x 64 x 64 spaces so that the network could learn volumetric patterns rather than two-dimensional images."] },
      { type: "dataGrid", label: "Voxel space", items: [{ label: "Resolution", value: "Approx. 64 x 64 x 64" }] },
      { type: "mediaGroup", groups: ["voxel"], fallbackGroups: ["diagram"], layout: "full", label: "VOXELISATION", placeholderCount: 1 },
      { type: "sectionTitle", number: "06", title: "Dataset A" },
      { type: "text", heading: "The first experiment and its limitations", paragraphs: ["Dataset A contained approximately 2,000 samples. A documented GAN architecture used a five-layer generator and four-layer discriminator and was trained for approximately 20,000 epochs. Although loss converged, many outputs did not form complete temple geometries."] },
      { type: "dataGrid", label: "Dataset A", items: [{ label: "Samples", value: "Approx. 2,000" }, { label: "Generator", value: "5 layers" }, { label: "Discriminator", value: "4 layers" }, { label: "Training", value: "Approx. 20,000 epochs" }] },
      { type: "mediaGroup", groups: ["dataset-a", "training"], fallbackGroups: ["analysis"], layout: "gallery", label: "DATASET A / TRAINING", placeholderCount: 4 },
      { type: "sectionTitle", number: "07", title: "Failure as Dataset Feedback" },
      { type: "text", heading: "Diagnosing the training data", paragraphs: ["Visual inspection revealed outliers, hollow geometry and inconsistent data. The unsuccessful outputs were used as feedback: problematic conditions were removed and the dataset was rebuilt with solid, filled geometries."] },
      { type: "flow", label: "Iterative research", steps: ["Dataset A", "Training", "Incomplete results", "Dataset inspection", "Outlier removal", "Filled geometries", "Dataset B"] },
      { type: "mediaGroup", groups: ["failure"], fallbackGroups: ["analysis"], layout: "asymmetric", label: "FAILED OUTPUTS / DIAGNOSIS", placeholderCount: 3 },
      { type: "sectionTitle", number: "08", title: "Final Dataset B" },
      { type: "text", heading: "Greater volumetric information", paragraphs: ["Dataset B contained approximately 600 filled geometries with greater diversity. Voxelising infill added depth resolution and texture to the volumetric representation."] },
      { type: "dataGrid", label: "Dataset B", items: [{ label: "Filled geometries", value: "Approx. 600" }, { label: "Change", value: "Solid / filled rather than hollow" }] },
      { type: "mediaGroup", groups: ["dataset-b"], fallbackGroups: ["dataset"], layout: "gallery", label: "FINAL DATASET B", placeholderCount: 4 },
      { type: "sectionTitle", number: "09", title: "Results" },
      { type: "text", heading: "Recognisable features and remaining weaknesses", paragraphs: ["Generated forms showed tapering profiles and cascading characteristics from the training data. Verandah-like lower portions still showed disconnects, and the stronger radial symmetry of Dataset A was reduced after greater diversity was introduced into Dataset B."] },
      { type: "dataGrid", label: "Result reading", items: [{ label: "Recognisable", value: "Tapering / cascading" }, { label: "Limitation", value: "Lower-part disconnects" }, { label: "Trade-off", value: "Reduced radial symmetry" }] },
      { type: "mediaGroup", groups: ["result", "animation"], fallbackGroups: ["gifs"], layout: "asymmetric", label: "GENERATED FORMS / GIF", placeholderCount: 3 },
      { type: "sectionTitle", number: "10", title: "Research Narrative" },
      { type: "flow", label: "Project sequence", steps: ["Architectural precedents", "Geometric abstraction", "Parametric dataset", "3D voxels", "GAN training", "Dataset diagnosis", "Retraining", "Generated forms", "Limitations"] },
    ],
  },
  {
    id: "charge-pavilion",
    number: "08",
    slug: "charge-pavilion",
    title: "Charge Pavilion",
    subtitle: "Minimal surfaces, differential growth and environmental response",
    year: "IAAC Winter 2021",
    type: "Academic Work",
    projectType: "Seminar / Studio Project",
    classification: "Academic",
    institution: "IAAC",
    institutionLink: "https://www.iaacblog.com/programs/charge-pavilion/",
    programme: "MaCAD",
    faculty: "Rodrigo Aguirre",
    assistants: ["Hesham Shawqy"],
    collaborators: ["Naitik Sharma", "Neil John Bersabe"],
    role: null,
    location: "Davao City, Philippines",
    keywords: ["Minimal Surfaces", "Differential Growth", "Galapagos", "Environmental Analysis", "Structural Analysis"],
    tags: ["Research", "Parametric", "Optimization", "Environmental Design", "Structural Design"],
    indexFocus: "Form Finding / Environmental Optimisation",
    shortDescription: "An environmentally responsive charging pavilion combining minimal-surface form finding with differential-growth shading.",
    introduction: ["Charge Pavilion combines minimal surfaces and differential growth to generate a continuous, environmentally responsive pavilion in Davao City.", "Minimal-surface form finding establishes the roof-column geometry, while environmental optimisation, structural analysis and a differential-growth shading layer respond to a hot tropical climate."],
    externalLinks: [{ label: "IAAC — Charge Pavilion", url: "https://www.iaacblog.com/programs/charge-pavilion/", kind: "Official Project Page" }],
    mediaCredit: "Official project documentation — IAAC",
    mediaFolder: "/projects/charge-pavilion",
    thumbnail: null,
    thumbnailType: "image",
    thumbnailAlt: "Charge Pavilion minimal surface and differential-growth layer",
    heroMedia: null,
    heroMediaType: "image",
    heroAlt: "Charge Pavilion in Davao City",
    featured: true,
    archive: true,
    placeholder: false,
    visualVariant: "assembly",
    content: [
      { type: "sectionTitle", number: "01", title: "Minimal Surface" },
      { type: "text", heading: "Continuous equilibrium geometry", paragraphs: ["A minimal surface attempts to minimise area within its boundary conditions. In the computational workflow, mesh topology, anchor points and relaxation goals produce a continuous geometry in which roof and column conditions merge."] },
      { type: "flow", label: "Form finding", steps: ["Define mesh topology", "Define anchor points", "Add relaxation goals", "Relax the mesh"] },
      { type: "mediaGroup", groups: ["minimal", "form"], fallbackGroups: ["process"], layout: "asymmetric", label: "MINIMAL SURFACE", placeholderCount: 3 },
      { type: "sectionTitle", number: "02", title: "Differential Growth" },
      { type: "text", heading: "Growth through local rules", paragraphs: ["Connected nodes remain close through attraction, nearby nodes maintain spacing through repulsion, and alignment regulates connected neighbours. Repeated iterations produce a branching and folding shading layer rather than random ornament."] },
      { type: "dataGrid", label: "Growth rules", items: ["Attraction", "Repulsion", "Alignment"] },
      { type: "mediaGroup", groups: ["growth", "animation"], fallbackGroups: ["diagram", "gifs"], layout: "asymmetric", label: "DIFFERENTIAL GROWTH / GIF", placeholderCount: 3 },
      { type: "sectionTitle", number: "03", title: "Precedents" },
      { type: "typologyGrid", items: [{ number: "01", title: "Thallus", description: "Zaha Hadid Architects: differential-growth-like articulation across a cylindrical surface." }, { number: "02", title: "Zephyr", description: "Marc Fornes / THEVERYMANY: rationalising topological geometry into a buildable mesh system." }] },
      { type: "sectionTitle", number: "04", title: "Site + Climate" },
      { type: "text", heading: "Maximising useful shade", paragraphs: ["Direct-radiation analysis identifies Davao City as generally hot through the year. The pavilion therefore combines vehicle charging with shaded occupied space and cooling opportunities."] },
      { type: "mediaGroup", groups: ["climate", "site"], fallbackGroups: ["analysis"], layout: "two-column", label: "SITE / RADIATION", placeholderCount: 2 },
      { type: "sectionTitle", number: "05", title: "Design Process" },
      { type: "flow", label: "Site to form", steps: ["Base site geometry", "Vehicular flow", "Entry points", "Internal vehicular path", "Setbacks", "Column boundary", "Minimal-surface form finding"] },
      { type: "mediaGroup", groups: ["design"], fallbackGroups: ["process"], layout: "gallery", label: "DESIGN PROCESS", placeholderCount: 4 },
      { type: "sectionTitle", number: "06", title: "Galapagos Optimisation" },
      { type: "text", heading: "Height, radiation and shade", paragraphs: ["Galapagos evolutionary optimisation was used to study structural height in relation to reducing solar radiation and increasing shaded area. It is not described as AI optimisation."] },
      { type: "mediaGroup", groups: ["optimisation"], fallbackGroups: ["analysis"], layout: "full", label: "GALAPAGOS OPTIMISATION", placeholderCount: 1 },
      { type: "sectionTitle", number: "07", title: "Structural / Topological Analysis" },
      { type: "text", heading: "Reading material demand", paragraphs: ["Displacement, utilisation, principal stress lines and material distribution were compared to locate high-demand regions, lower-demand regions and possible areas for material redistribution."] },
      { type: "dataGrid", label: "Documented structural setup", items: [{ label: "Maximum displacement", value: "Approx. 1.48 cm" }, { label: "Total mass", value: "Approx. 1,400 t" }, { label: "Material", value: "Concrete" }, { label: "Shell cross-section", value: "Approx. 150 mm" }] },
      { type: "mediaGroup", groups: ["structural", "analysis"], fallbackGroups: ["diagram"], layout: "gallery", label: "STRUCTURAL ANALYSIS", placeholderCount: 4 },
      { type: "sectionTitle", number: "08", title: "Principal Stress Lines" },
      { type: "text", heading: "Force-transfer paths", paragraphs: ["Principal-stress analysis identifies high-demand and lower-demand regions and helps establish where material may be reduced or redistributed."] },
      { type: "mediaGroup", groups: ["stress"], fallbackGroups: ["analysis"], layout: "full", label: "PRINCIPAL STRESS LINES", placeholderCount: 1 },
      { type: "sectionTitle", number: "09", title: "Surface Differential Growth" },
      { type: "flow", label: "Growth workflow", steps: ["Segment curves", "Attach to surface", "Segment-length goal", "Collision goals", "Angle goals", "Iterative growth"] },
      { type: "dataGrid", label: "Seed geometries", items: ["Circle", "Center Flower", "Border Jitter", "Full Vertical Streaks"] },
      { type: "mediaGroup", groups: ["growth"], fallbackGroups: ["process"], layout: "gallery", label: "GROWTH STUDIES", placeholderCount: 4 },
      { type: "sectionTitle", number: "10", title: "Simulation Parameters" },
      { type: "dataGrid", label: "Documented parameters", items: [{ label: "Divide Curve Count", value: "1000" }, { label: "OnMesh Strength", value: "1000" }, { label: "Collider Radius", value: "1.10" }, { label: "Collider Strength", value: "100" }, { label: "Angle Rest Angle", value: "0" }, { label: "Angle Strength", value: "1500" }] },
      { type: "sectionTitle", number: "11", title: "Final Project" },
      { type: "flow", label: "Project sequence", steps: ["Climate", "Site", "Minimal surface", "Solar optimisation", "Structural analysis", "Differential growth", "Permeable shade", "Final pavilion"] },
      { type: "mediaGroup", groups: ["final", "model"], fallbackGroups: ["result"], layout: "asymmetric", label: "FINAL PAVILION", placeholderCount: 3 },
    ],
  },
  {
    id: "above-and-inbetween",
    number: "09",
    slug: "above-and-inbetween",
    title: "Above & Inbetween",
    subtitle: "Eco-parametric infrastructure for Dharavi",
    year: "IAAC Winter 2021",
    type: "Academic Work",
    projectType: "Studio Project",
    classification: "Academic",
    institution: "IAAC",
    programme: "MaCAD",
    studio: "Advanced Computation for Environmental and Structural Design",
    faculty: "Arthur Mamou-Mani",
    assistants: ["Fun Yuen", "Krishna Bhat"],
    collaborators: ["Lucie Ketelsen", "Naitik Sharma", "Takeaki Sakakibara", "Varun Mehta"],
    role: null,
    location: "Dharavi, Mumbai, India",
    keywords: ["Urban Systems", "Cellular Automata", "Environmental Design", "Bamboo Structure", "Agrovoltaics"],
    tags: ["Research", "Urban Systems", "Cellular Automata", "Environmental Design", "Structural Design"],
    indexFocus: "Cellular Automata / Urban Infrastructure",
    shortDescription: "A bottom-up computational system for lightweight bamboo, solar and agrovoltaic infrastructure above Dharavi’s existing fabric.",
    introduction: ["Above & Inbetween proposes an eco-parametric infrastructure that grows above and between Dharavi’s existing informal buildings without replacing the neighbourhood fabric.", "Two-dimensional and spatial Cellular Automata generate elevated floor plates and a bamboo lattice in response to access, rooftop use, solar infrastructure, agriculture and local structural conditions."],
    externalLinks: [],
    mediaFolder: "/projects/above-and-inbetween",
    thumbnail: null,
    thumbnailType: "image",
    thumbnailAlt: "Above and Inbetween cellular-automata infrastructure in Dharavi",
    heroMedia: null,
    heroMediaType: "image",
    heroAlt: "Bamboo and agrovoltaic infrastructure above Dharavi",
    featured: false,
    archive: true,
    placeholder: false,
    visualVariant: "matrix",
    content: [
      { type: "sectionTitle", number: "01", title: "Understanding Dharavi" },
      { type: "text", heading: "Working with existing urban fabric", paragraphs: ["The study records corrugated roofs, tarpaulin, mild-steel frames, bamboo scaffolding, timber, water drums, vertical circulation, roof occupation, utilities, recycling networks, workshops and shared spaces. The site is treated as an active material and social system, not empty land."] },
      { type: "mediaGroup", groups: ["context", "dharavi"], fallbackGroups: ["overview"], layout: "asymmetric", label: "EXISTING DHARAVI", placeholderCount: 3 },
      { type: "sectionTitle", number: "02", title: "Rooftop Opportunity" },
      { type: "text", heading: "Activating the upper layer", paragraphs: ["Stronger masonry, RCC and steel conditions often sit below lightweight vulnerable roofs. The project investigates pedestrian access, community space, solar infrastructure and agriculture above existing buildings rather than demolition and reconstruction."] },
      { type: "mediaGroup", groups: ["rooftop"], fallbackGroups: ["diagram"], layout: "two-column", label: "ROOFTOP OPPORTUNITY", placeholderCount: 2 },
      { type: "sectionTitle", number: "03", title: "Case-Site Data" },
      { type: "text", heading: "A pocket adjacent to Kumbharwada", paragraphs: ["Four significant in-between spaces were identified as possible community pockets mediating between local interventions and the larger urban system."] },
      { type: "dataGrid", label: "Documented site data", items: [{ label: "Houses", value: "Approx. 175" }, { label: "Residents", value: "Approx. 1,400-1,500" }, { label: "Site area", value: "Approx. 6,000 m²" }, { label: "In-between spaces", value: "Approx. 329 m²" }, { label: "Share of site", value: "Approx. 6%" }] },
      { type: "mediaGroup", groups: ["site"], fallbackGroups: ["analysis"], layout: "full", label: "CASE SITE", placeholderCount: 1 },
      { type: "sectionTitle", number: "04", title: "Programmatic Instances" },
      { type: "dataGrid", label: "Four conditions", items: ["Access", "Rooftop", "Solar", "Agriculture"] },
      { type: "sectionTitle", number: "05", title: "Why Cellular Automata?" },
      { type: "text", heading: "Local rules and emergent form", paragraphs: ["Dharavi’s morphology can be understood as emerging from many local decisions rather than one central masterplan. A Cellular Automata model similarly produces larger patterns through repeated local rules, with cell state determined by neighbouring cells."] },
      { type: "dataGrid", label: "Basic state", items: [{ label: "0", value: "Dead" }, { label: "1", value: "Alive" }] },
      { type: "mediaGroup", groups: ["ca", "cellular"], fallbackGroups: ["diagram"], layout: "full", label: "CELLULAR AUTOMATA", placeholderCount: 1 },
      { type: "sectionTitle", number: "06", title: "2D Cellular Automata" },
      { type: "text", heading: "Generating elevated floor plates", paragraphs: ["A site-boundary grid was iterated six times using nine neighbours, with one minimum and three maximum alive neighbours. The resulting floor plate retains irregularity and variation above the settlement."] },
      { type: "dataGrid", label: "Documented 2D CA", items: [{ label: "Iterations", value: "6" }, { label: "Neighbours", value: "9" }, { label: "Minimum alive", value: "1" }, { label: "Maximum alive", value: "3" }] },
      { type: "mediaGroup", groups: ["ca2d", "animation"], fallbackGroups: ["analysis", "gifs"], layout: "gallery", label: "2D CA / GIF", placeholderCount: 3 },
      { type: "sectionTitle", number: "07", title: "2.5D / 3D Cellular Automata" },
      { type: "text", heading: "Extending generations vertically", paragraphs: ["Successive CA generations grow from the floor-plate boundaries and are plotted along the vertical axis to create a spatial lattice. The source uses both 2.5D and 3D terminology; the project retains that distinction rather than artificially reconciling it."] },
      { type: "mediaGroup", groups: ["ca3d", "spatial"], fallbackGroups: ["process"], layout: "asymmetric", label: "SPATIAL CA", placeholderCount: 3 },
      { type: "sectionTitle", number: "08", title: "Climate + Solar Potential" },
      { type: "text", heading: "Solar opportunity and monsoon variation", paragraphs: ["The source documents more than approximately 2,500 hours of direct sunlight annually, approximately 6.8 hours per day, reduced monsoon-period production, high radiation and useful southern PV inclination."] },
      { type: "dataGrid", label: "Documented solar context", items: [{ label: "Direct sunlight", value: "> approx. 2,500 h/year" }, { label: "Daily sunlight", value: "Approx. 6.8 h/day" }] },
      { type: "mediaGroup", groups: ["solar", "climate"], fallbackGroups: ["analysis"], layout: "gallery", label: "SOLAR POTENTIAL", placeholderCount: 3 },
      { type: "sectionTitle", number: "09", title: "Energy-Generation Scenario" },
      { type: "text", heading: "A project calculation, not a present-day claim", paragraphs: ["The figures below are preserved as the source portfolio’s scenario for the selected neighbourhood pocket; their units are not silently corrected."] },
      { type: "dataGrid", label: "Source calculation", items: [{ label: "Single-cell generation", value: "1,763 kW/hr per year" }, { label: "Site pocket", value: "58,179 kW/hr per year" }, { label: "System", value: "73 kW" }, { label: "Household comparison", value: "Approx. 175 households" }] },
      { type: "mediaGroup", groups: ["energy"], fallbackGroups: ["analysis"], layout: "full", label: "ENERGY SCENARIO", placeholderCount: 1 },
      { type: "sectionTitle", number: "10", title: "Bamboo Structural System" },
      { type: "text", heading: "Connecting to suitable existing supports", paragraphs: ["Floor, pillar and existing wall-edge conditions organise the bamboo system. A Shortest Walk strategy identifies support relationships, and supports are treated as pinned in the structural model."] },
      { type: "flow", label: "Structural layers", steps: ["Floor", "Pillar", "Existing wall edge / support", "Shortest Walk", "Pinned support"] },
      { type: "mediaGroup", groups: ["structure", "bamboo"], fallbackGroups: ["technical"], layout: "asymmetric", label: "BAMBOO STRUCTURE", placeholderCount: 3 },
      { type: "sectionTitle", number: "11", title: "Connection System" },
      { type: "dataGrid", label: "Bamboo joints", items: ["Bundle Joints", "Cross Joints", "Angle Joints"] },
      { type: "mediaGroup", groups: ["connection", "joint"], fallbackGroups: ["technical"], layout: "three-column", label: "CONNECTIONS", placeholderCount: 3 },
      { type: "sectionTitle", number: "12", title: "Structural Iteration" },
      { type: "text", heading: "Adding support only where demand increases", paragraphs: ["An initial strategy used approximately four pillars at each section. The later strategy maintained approximately two pillars globally and added three locally in high-deformation zones, reducing total self-weight by more than approximately 2,000 kg while maintaining acceptable analysed behaviour."] },
      { type: "dataGrid", label: "Structural refinement", items: [{ label: "Initial", value: "Approx. 4 pillars / section" }, { label: "Later global", value: "Approx. 2 pillars" }, { label: "Local reinforcement", value: "3 pillars" }, { label: "Self-weight reduction", value: "> approx. 2,000 kg" }] },
      { type: "mediaGroup", groups: ["structural", "iteration"], fallbackGroups: ["analysis"], layout: "gallery", label: "STRUCTURAL ITERATION", placeholderCount: 4 },
      { type: "sectionTitle", number: "13", title: "Eco-Parametric Infrastructure" },
      { type: "flow", label: "Urban-scale sequence", steps: ["Existing Dharavi", "Rooftop opportunity", "Programmes", "2D CA", "Elevated floor plate", "Spatial CA", "Bamboo lattice", "Solar + agriculture", "Structural adaptation"] },
      { type: "mediaGroup", groups: ["final"], fallbackGroups: ["result"], layout: "asymmetric", label: "FINAL INFRASTRUCTURE", placeholderCount: 3 },
    ],
  },
  {
    id: "rhizome-space-habitat",
    number: "10",
    slug: "rhizome-space-habitat",
    title: "Rhizome",
    subtitle: "Infrastructure as Public Space",
    year: "2021—2022",
    type: "Academic Work",
    projectType: "Studio / Seminar Project",
    classification: "Academic",
    institution: "IAAC",
    institutionLink: "https://www.iaacblog.com/programs/rhizome-3/",
    programme: "MaCAD",
    studio: "BIM and Smart Construction Studio",
    faculty: "Xavier De Kestelier",
    assistants: ["Joanna Maria Lesna", "Levent Ozruh"],
    collaborators: ["Clemens Russ", "Naitik Sharma", "Oluwadamilola Akinniyi"],
    role: null,
    location: "Low Earth Orbit",
    keywords: ["BIM", "Space Architecture", "Modular Systems", "Life Support", "Growth Systems"],
    tags: ["Research", "BIM", "Space Architecture", "Modular Systems"],
    indexFocus: "BIM / Modular Space Habitats",
    shortDescription: "A modular low-Earth-orbit habitat designed to grow from a six-person outpost into infrastructure for 148 residents.",
    introduction: ["Rhizome imagines a low-Earth-orbit station that grows from six residents to 148 through a repeatable kit of living, working, greenhouse, recreation and infrastructure modules.", "The proposal combines BIM coordination, modular growth, environmental control, energy generation and shared public space into an expandable orbital masterplan."],
    externalLinks: [{ label: "IAAC — RHIZOME", url: "https://www.iaacblog.com/programs/rhizome-3/", kind: "Official Project Page" }],
    mediaCredit: "Official project documentation — IAAC",
    mediaFolder: "/projects/rhizome-space-habitat",
    thumbnail: null,
    thumbnailType: "image",
    thumbnailAlt: "Rhizome expandable orbital habitat",
    heroMedia: null,
    heroMediaType: "image",
    heroAlt: "Rhizome modular space station in low Earth orbit",
    featured: true,
    archive: true,
    placeholder: false,
    visualVariant: "orbital",
    content: [
      { type: "sectionTitle", number: "01", title: "Orbital Context" },
      { type: "text", heading: "A habitat in low Earth orbit", paragraphs: ["The project begins with orbital context, access, radiation, microgravity and the operational constraints of building beyond Earth. The station is approached as a long-term settlement rather than a single finished object."] },
      { type: "mediaGroup", groups: ["orbit", "context"], fallbackGroups: ["overview"], layout: "asymmetric", label: "ORBITAL CONTEXT", placeholderCount: 3 },
      { type: "sectionTitle", number: "02", title: "Site Selection Metrics" },
      { type: "dataGrid", label: "Comparative criteria", items: ["Access and resupply", "Radiation exposure", "Orbital stability", "Communication", "Energy potential", "Expansion capacity"] },
      { type: "mediaGroup", groups: ["selection", "analysis"], fallbackGroups: ["diagram"], layout: "two-column", label: "SITE SELECTION", placeholderCount: 2 },
      { type: "sectionTitle", number: "03", title: "From Surviving to Thriving" },
      { type: "text", heading: "Beyond minimum life support", paragraphs: ["The brief expands from survival requirements toward social, spatial and psychological wellbeing. Living, working, food production, recreation and shared civic space become interconnected parts of the habitat system."] },
      { type: "flow", label: "Habitat ambition", steps: ["Survive", "Stabilise", "Connect", "Grow", "Thrive"] },
      { type: "sectionTitle", number: "04", title: "Infrastructure as Public Space" },
      { type: "text", heading: "A decentralised resource network", paragraphs: ["Resource systems are distributed through the station and made legible as shared infrastructure. Nodes and corridors organise exchange while larger programme modules create public destinations within the network."] },
      { type: "dataGrid", label: "Three linked layers", items: ["Resources", "Decentralised network", "Public space"] },
      { type: "mediaGroup", groups: ["infrastructure", "network"], fallbackGroups: ["diagram"], layout: "full", label: "PUBLIC INFRASTRUCTURE", placeholderCount: 1 },
      { type: "sectionTitle", number: "05", title: "Population Growth" },
      { type: "text", heading: "An eight-stage expansion sequence", paragraphs: ["The masterplan grows incrementally, allowing new modules, resource capacity and public programmes to arrive with the population."] },
      { type: "dataGrid", label: "Residents by stage", items: ["6", "12", "24", "48", "56", "100", "124", "148"] },
      { type: "mediaGroup", groups: ["growth", "animation"], fallbackGroups: ["sequence", "gifs"], layout: "gallery", label: "GROWTH SEQUENCE / GIF", placeholderCount: 4 },
      { type: "sectionTitle", number: "06", title: "Module Catalogue" },
      { type: "dataGrid", label: "Programme modules", items: ["Greenhouse", "Recreation", "Work", "Living", "Node", "Corridor", "Infrastructure"] },
      { type: "mediaGroup", groups: ["module", "catalogue"], fallbackGroups: ["diagram"], layout: "gallery", label: "MODULE CATALOGUE", placeholderCount: 4 },
      { type: "sectionTitle", number: "07", title: "Life-Support Systems" },
      { type: "dataGrid", label: "Integrated systems", items: ["Water", "Waste", "Air", "Pressure", "Interface", "Energy + fuel", "Food", "Communications", "Temperature + radiation"] },
      { type: "mediaGroup", groups: ["lifesupport", "systems"], fallbackGroups: ["technical"], layout: "asymmetric", label: "LIFE SUPPORT", placeholderCount: 3 },
      { type: "sectionTitle", number: "08", title: "Modular Geometry" },
      { type: "text", heading: "A repeatable spatial and structural logic", paragraphs: ["A consistent geometric system allows different programmes to share connections, structure and service interfaces while retaining spatial variation."] },
      { type: "mediaGroup", groups: ["geometry"], fallbackGroups: ["process"], layout: "asymmetric", label: "MODULAR GEOMETRY", placeholderCount: 3 },
      { type: "sectionTitle", number: "09", title: "Kit of Parts" },
      { type: "dataGrid", label: "Construction components", items: ["Main structure", "Perforated rib", "Corner casts", "Insulation panels", "Exchangeable windows + hatches", "Connection hatches"] },
      { type: "mediaGroup", groups: ["kit", "parts"], fallbackGroups: ["technical"], layout: "gallery", label: "KIT OF PARTS", placeholderCount: 4 },
      { type: "sectionTitle", number: "10", title: "ECLSS + MEP" },
      { type: "dataGrid", label: "Coordinated services", items: ["HVAC", "Power", "Data", "Radiators", "Water", "Hydrogen"] },
      { type: "mediaGroup", groups: ["eclss", "mep"], fallbackGroups: ["systems"], layout: "two-column", label: "ECLSS / MEP", placeholderCount: 2 },
      { type: "sectionTitle", number: "11", title: "Spatial Configurations" },
      { type: "dataGrid", label: "Module variants", items: ["Arena", "Loft", "Offset Core", "Two Levels"] },
      { type: "mediaGroup", groups: ["configuration"], fallbackGroups: ["interior"], layout: "gallery", label: "CONFIGURATIONS", placeholderCount: 4 },
      { type: "sectionTitle", number: "12", title: "Energy Infrastructure" },
      { type: "flow", label: "Energy sequence", steps: ["Habitat aggregation", "Heat collection", "Radiators", "Solar array", "Distribution"] },
      { type: "mediaGroup", groups: ["energy", "solar"], fallbackGroups: ["systems"], layout: "asymmetric", label: "ENERGY SYSTEM", placeholderCount: 3 },
      { type: "sectionTitle", number: "13", title: "Masterplan + BIM" },
      { type: "text", heading: "One coordinated growth model", paragraphs: ["The module catalogue, service systems, public-space logic and population stages are assembled in a coordinated BIM masterplan that can be checked as the station expands."] },
      { type: "mediaGroup", groups: ["masterplan", "bim"], fallbackGroups: ["final"], layout: "asymmetric", label: "BIM MASTERPLAN", placeholderCount: 3 },
      { type: "sectionTitle", number: "14", title: "Collaboration Workflow" },
      { type: "flow", label: "Shared workflow", steps: ["Common brief", "Module ownership", "Shared BIM model", "System coordination", "Clash review", "Masterplan integration"] },
      { type: "mediaGroup", groups: ["workflow", "final"], fallbackGroups: ["result"], layout: "full", label: "FINAL HABITAT", placeholderCount: 1 },
    ],
  },
  {
    id: "environmental-studies-sydney",
    number: "11",
    slug: "environmental-studies-sydney",
    title: "Environmental Studies",
    subtitle: "Climate-responsive massing in Sydney",
    year: null,
    type: "Academic Study",
    projectType: "Environmental Design Study / Seminar Study",
    classification: "Academic",
    institution: "IAAC",
    studio: null,
    faculty: null,
    assistants: [],
    collaborators: [],
    role: null,
    location: "Sydney, Australia",
    keywords: ["Environmental Design", "Climate Analysis", "Daylight", "Solar Radiation", "UTCI"],
    tags: ["Research", "Environmental", "Climate Analysis", "Performance Design"],
    indexFocus: "Environmental Analysis / Sydney",
    shortDescription: "A climate-led study testing massing, daylight, wind, glare and outdoor comfort for a Sydney building proposal.",
    introduction: ["This environmental study develops a Sydney building proposal through climate data, solar exposure, daylight, glare, wind and outdoor-comfort analysis.", "Successive massing options respond to a humid subtropical climate by balancing summer shade, winter sun, natural ventilation and useful daylight."],
    externalLinks: [],
    mediaFolder: "/projects/environmental-studies-sydney",
    thumbnail: null,
    thumbnailType: "image",
    thumbnailAlt: "Sydney environmental design analysis",
    heroMedia: null,
    heroMediaType: "image",
    heroAlt: "Climate responsive building study in Sydney",
    featured: false,
    archive: true,
    placeholder: false,
    visualVariant: "climate",
    content: [
      { type: "sectionTitle", number: "01", title: "Climate" },
      { type: "text", heading: "Humid subtropical Sydney", paragraphs: ["Sydney is classified as humid subtropical (Cfa) in the source, with warm, relatively hot and humid summers, cooler winters and an acknowledged urban heat-island condition."] },
      { type: "mediaGroup", groups: ["climate", "context"], fallbackGroups: ["analysis"], layout: "gallery", label: "CLIMATE CONTEXT", placeholderCount: 4 },
      { type: "sectionTitle", number: "02", title: "Temperature" },
      { type: "text", heading: "Seasonal variation", paragraphs: ["Average temperatures in the source vary from approximately 12 degrees Celsius in winter to 23 degrees Celsius in summer, with broadly similar daily fluctuation patterns through the seasons."] },
      { type: "dataGrid", label: "Temperature range", items: [{ label: "Winter", value: "Approx. 12 C" }, { label: "Summer", value: "Approx. 23 C" }] },
      { type: "mediaGroup", groups: ["temperature"], fallbackGroups: ["climate"], layout: "two-column", label: "TEMPERATURE", placeholderCount: 2 },
      { type: "sectionTitle", number: "03", title: "Relative Humidity" },
      { type: "text", heading: "Daily and seasonal humidity", paragraphs: ["Humidity is highest in late summer and autumn. Monthly averages are above approximately 57 percent, tending to peak at night, fall toward midday and rise again."] },
      { type: "dataGrid", label: "Monthly average", items: [{ label: "Relative humidity", value: "> approx. 57%" }] },
      { type: "mediaGroup", groups: ["humidity"], fallbackGroups: ["climate"], layout: "two-column", label: "RELATIVE HUMIDITY", placeholderCount: 2 },
      { type: "sectionTitle", number: "04", title: "Solar Radiation" },
      { type: "text", heading: "Direct, diffuse and global radiation", paragraphs: ["Direct solar radiation is highest during summer and lower during winter. The source compares direct, diffuse and global radiation with sky-cover conditions."] },
      { type: "mediaGroup", groups: ["radiation", "solar"], fallbackGroups: ["analysis"], layout: "gallery", label: "SOLAR RADIATION", placeholderCount: 4 },
      { type: "sectionTitle", number: "05", title: "Wind" },
      { type: "text", heading: "Seasonal wind direction", paragraphs: ["Winds are predominantly western during the May-to-September heating period. During the December-to-March cooling period they shift toward the north-east and south, with speeds reaching approximately 10 metres per second."] },
      { type: "dataGrid", label: "Wind summary", items: [{ label: "May-September", value: "Predominantly west" }, { label: "December-March", value: "North-east / south" }, { label: "Cooling-period speed", value: "Up to approx. 10 m/s" }] },
      { type: "mediaGroup", groups: ["wind"], fallbackGroups: ["analysis"], layout: "gallery", label: "WIND", placeholderCount: 3 },
      { type: "sectionTitle", number: "06", title: "HDD / CDD + Thermal Comfort" },
      { type: "text", heading: "Degree days are not the whole picture", paragraphs: ["Heating and Cooling Degree Days initially suggest greater heating demand, but the study notes that these indicators do not adequately capture humidity. UTCI gives a more detailed picture and indicates that high temperatures remain a significant comfort concern."] },
      { type: "mediaGroup", groups: ["hdd", "utci"], fallbackGroups: ["comfort"], layout: "two-column", label: "THERMAL COMFORT", placeholderCount: 2 },
      { type: "sectionTitle", number: "07", title: "Effect of Shade + Wind" },
      { type: "text", heading: "Shade is the stronger hot-weather intervention", paragraphs: ["Sun and shade are tested with and without wind. Both affect comfort, but shade has the more substantial effect during hot conditions; wind can improve summer comfort while worsening colder conditions."] },
      { type: "dataGrid", label: "Compared conditions", items: ["Sun + no wind", "Shade + no wind", "Sun + wind", "Shade + wind"] },
      { type: "mediaGroup", groups: ["shade", "comfort"], fallbackGroups: ["analysis"], layout: "gallery", label: "SHADE + WIND", placeholderCount: 4 },
      { type: "sectionTitle", number: "08", title: "Site Model" },
      { type: "text", heading: "Downtown Sydney as an environmental field", paragraphs: ["The selected site is modelled with its surrounding buildings because nearby urban geometry affects sunlight, shade, wind, downdraft and local comfort."] },
      { type: "mediaGroup", groups: ["site", "context"], fallbackGroups: ["model"], layout: "asymmetric", label: "SITE MODEL", placeholderCount: 3 },
      { type: "sectionTitle", number: "09", title: "Sun Path" },
      { type: "text", heading: "Northern solar orientation", paragraphs: ["Because Sydney lies in the Southern Hemisphere, the source identifies the sun path as predominantly inclined toward the north."] },
      { type: "mediaGroup", groups: ["sunpath"], fallbackGroups: ["solar"], layout: "two-column", label: "SUN PATH", placeholderCount: 2 },
      { type: "sectionTitle", number: "10", title: "Site Irradiation" },
      { type: "text", heading: "Seasonal exposure in the urban context", paragraphs: ["Representative dates distinguish heating and cooling periods. Greater sunlight occurs at street edges and openings aligned with less obstructed east-west corridors."] },
      { type: "dataGrid", label: "Study dates", items: ["21 December", "21 June", "20 March", "23 September"] },
      { type: "mediaGroup", groups: ["irradiation", "seasonal"], fallbackGroups: ["solar"], layout: "gallery", label: "SITE IRRADIATION", placeholderCount: 4 },
      { type: "sectionTitle", number: "11", title: "Massing Studies" },
      { type: "text", heading: "Allow winter sun and reduce summer sun", paragraphs: ["Two broad massing strategies connect hand-drawn environmental reasoning to simulated geometry. Orientation, depth and opening conditions are tested before detailed facade development."] },
      { type: "mediaGroup", groups: ["massing", "sketch"], fallbackGroups: ["process"], layout: "asymmetric", label: "MASSING STUDIES", placeholderCount: 3 },
      { type: "sectionTitle", number: "12", title: "Option 01: Daylight Iteration" },
      { type: "text", heading: "Starting mass to light shelves to atrium", paragraphs: ["A glazing ratio of approximately 0.5 left significant areas of the deep plan below an approximate daylight factor of 2. Light shelves improved distribution, but the central hall remained weak. Introducing an atrium substantially improved daylight across the floor plate."] },
      { type: "dataGrid", label: "Three-step iteration", items: [{ label: "01", value: "Starting mass / glazing ratio 0.5" }, { label: "02", value: "Light shelves" }, { label: "03", value: "Central atrium" }] },
      { type: "mediaGroup", groups: ["option1", "lightshelf", "atrium"], fallbackGroups: ["daylight"], layout: "gallery", label: "OPTION 01", placeholderCount: 4 },
      { type: "sectionTitle", number: "13", title: "Option 02" },
      { type: "text", heading: "A shallower daylight strategy", paragraphs: ["The second option uses a shallower floor plan and improves daylight penetration, especially toward the north. Most rooms except the hall show stronger daylight autonomy, but north-facing glare remains a concern."] },
      { type: "mediaGroup", groups: ["option2", "glare"], fallbackGroups: ["daylight"], layout: "asymmetric", label: "OPTION 02", placeholderCount: 3 },
      { type: "sectionTitle", number: "14", title: "Wind Analysis: Heating Period" },
      { type: "text", heading: "Wind corridors, shadows and downdraft", paragraphs: ["CFD studies identify ground-plane speeds above approximately 7.6 metres per second in some areas. Wind corridors, facade acceleration, wind shadows and downdraft are read in relation to the proposal and surrounding buildings."] },
      { type: "dataGrid", label: "Heating-period condition", items: [{ label: "Ground-plane wind", value: "> approx. 7.6 m/s in some areas" }] },
      { type: "mediaGroup", groups: ["heating", "wind"], fallbackGroups: ["analysis"], layout: "gallery", label: "HEATING-PERIOD WIND", placeholderCount: 3 },
      { type: "sectionTitle", number: "15", title: "Wind Analysis: Cooling Period" },
      { type: "text", heading: "Managing summer airflow", paragraphs: ["North-eastern and southern winds create problematic corridors and vertical acceleration around some facades. Vegetation, facade openings, ground-level permeability and controlled east-west porosity are investigated without eliminating useful ventilation."] },
      { type: "mediaGroup", groups: ["cooling", "wind"], fallbackGroups: ["analysis"], layout: "gallery", label: "COOLING-PERIOD WIND", placeholderCount: 3 },
      { type: "sectionTitle", number: "16", title: "Comfort Analysis" },
      { type: "text", heading: "Summer heat and winter exposure", paragraphs: ["The documented summer extreme reaches an approximate UTCI of 51 degrees Celsius. Vegetation improves conditions but cannot guarantee comfort without additional shade; winter produces a separate low-perceived-temperature challenge."] },
      { type: "dataGrid", label: "Extreme tested condition", items: [{ label: "Summer UTCI", value: "Approx. 51 C" }] },
      { type: "mediaGroup", groups: ["comfort", "utci"], fallbackGroups: ["analysis"], layout: "gallery", label: "COMFORT ANALYSIS", placeholderCount: 3 },
      { type: "sectionTitle", number: "17", title: "Conclusion" },
      { type: "text", heading: "Shading is the strongest intervention", paragraphs: ["High temperature is the major environmental challenge in the documented study. Shading has the strongest effect, but it must be designed without blocking the ventilation that supports comfort during warmer periods."] },
      { type: "flow", label: "Balanced environmental design", steps: ["Sun", "Shade", "Daylight", "Glare", "Wind", "Thermal comfort"] },
      { type: "mediaGroup", groups: ["final", "proposal"], fallbackGroups: ["result"], layout: "full", label: "ENVIRONMENTAL DESIGN CONCLUSION", placeholderCount: 1 },
    ],
  },
  {
    id: "structural-studies-dharavi",
    number: "12",
    slug: "structural-studies-dharavi",
    title: "Structural Studies",
    subtitle: "Dharavi Bridge Catalogue",
    year: null,
    type: "Academic Study",
    projectType: "Structural Design Study / Seminar Study",
    classification: "Academic",
    institution: "IAAC",
    studio: null,
    faculty: null,
    assistants: [],
    collaborators: [],
    role: null,
    location: "Dharavi, Mumbai, India",
    keywords: ["Structural Design", "Shell Structures", "Bridge Design", "Karamba", "Parametric Analysis"],
    tags: ["Research", "Structural", "Bridge Design", "Parametric Design"],
    indexFocus: "Structural Optimisation / Bridge Catalogue",
    shortDescription: "A parametric catalogue comparing shell-bridge geometries through displacement, utilisation, stress and force flow.",
    introduction: ["This structural catalogue tests a family of pedestrian shell bridges for a 48-metre span in Dharavi.", "Three geometric studies compare symmetric, asymmetric and three-legged systems through common load cases and performance metrics, making trade-offs visible rather than selecting form by appearance alone."],
    externalLinks: [],
    mediaFolder: "/projects/structural-studies-dharavi",
    thumbnail: null,
    thumbnailType: "image",
    thumbnailAlt: "Dharavi structural bridge catalogue",
    heroMedia: null,
    heroMediaType: "image",
    heroAlt: "Parametric shell bridge structural analysis",
    featured: false,
    archive: true,
    placeholder: false,
    visualVariant: "structural",
    content: [
      { type: "sectionTitle", number: "01", title: "Design Catalogue" },
      { type: "text", heading: "A structural design space", paragraphs: ["The catalogue compares three-legged and four-legged shells, symmetric and asymmetric support configurations, and different surface-area distributions as samples within a larger bridge design space."] },
      { type: "dataGrid", label: "Variation families", items: ["3-legged", "4-legged", "Symmetric", "Asymmetric"] },
      { type: "mediaGroup", groups: ["catalogue", "brief"], fallbackGroups: ["overview"], layout: "gallery", label: "DESIGN CATALOGUE", placeholderCount: 4 },
      { type: "sectionTitle", number: "02", title: "Form Finding" },
      { type: "text", heading: "Relaxed and inflated meshes", paragraphs: ["Flat meshes are relaxed and inflated with Kangaroo to create smooth doubly curved shells, then transferred into Karamba for structural analysis."] },
      { type: "flow", label: "Geometry workflow", steps: ["Flat mesh", "Relax", "Inflate", "Doubly curved shell", "Karamba model"] },
      { type: "mediaGroup", groups: ["formfinding", "kangaroo", "animation"], fallbackGroups: ["process"], layout: "asymmetric", label: "FORM FINDING / GIF", placeholderCount: 3 },
      { type: "sectionTitle", number: "03", title: "Precedents" },
      { type: "text", heading: "Curvature and structural behaviour", paragraphs: ["Striatus by Zaha Hadid Architects establishes a doubly curved, compression-oriented 3D-printed concrete precedent. The Maya Somaiya Library by sP+a provides a compression-dominant Catalan-vault reference using masonry and tile construction."] },
      { type: "mediaGroup", groups: ["precedent"], fallbackGroups: ["reference"], layout: "two-column", label: "STRUCTURAL PRECEDENTS", placeholderCount: 2 },
      { type: "sectionTitle", number: "04", title: "Structural Principles" },
      { type: "text", heading: "Geometry redirects force", paragraphs: ["Unlike a flat beam spanning between columns, the curved shell can redirect demand toward the supports through compressive and membrane action. The study uses this principle to read where each geometry works and where it becomes inefficient."] },
      { type: "mediaGroup", groups: ["principle", "sketch"], fallbackGroups: ["diagram"], layout: "full", label: "STRUCTURAL PRINCIPLES", placeholderCount: 1 },
      { type: "sectionTitle", number: "05", title: "Analysis Setup" },
      { type: "dataGrid", label: "Common parameters", items: [{ label: "Span", value: "48 m" }, { label: "Live load", value: "7.5 kN/m2" }, { label: "Wind load", value: "1 kN/m2" }, { label: "Shell cross section", value: "250 mm" }, { label: "Material", value: "Concrete" }] },
      { type: "dataGrid", label: "Load cases", items: [{ label: "00", value: "Self weight" }, { label: "01", value: "Live load" }, { label: "02", value: "Wind Y" }, { label: "03", value: "Wind X" }] },
      { type: "mediaGroup", groups: ["setup", "load"], fallbackGroups: ["technical"], layout: "gallery", label: "ANALYSIS SETUP", placeholderCount: 4 },
      { type: "sectionTitle", number: "06", title: "Evaluation Metrics" },
      { type: "dataGrid", label: "Repeated analysis categories", items: ["Displacement", "Utilisation", "Principal stresses", "Force flow"] },
      { type: "mediaGroup", groups: ["metrics", "analysis"], fallbackGroups: ["diagram"], layout: "gallery", label: "EVALUATION METRICS", placeholderCount: 4 },
      { type: "sectionTitle", number: "07", title: "Study 01: Symmetrical Four-Legged Structures" },
      { type: "text", heading: "Four-legged lower-area direction", paragraphs: ["The first study compares symmetric bridge families. Variation 01, a four-legged form with a lower overall area, provides the preferred balance within this set."] },
      { type: "mediaGroup", groups: ["study1", "symmetric"], fallbackGroups: ["analysis"], layout: "gallery", label: "STUDY 01", placeholderCount: 4 },
      { type: "sectionTitle", number: "08", title: "Principal Stresses: Study 01" },
      { type: "text", heading: "Arch-like stress paths", paragraphs: ["Under gravity, force paths move from central regions toward the legs: compression follows support directions while tension develops where the shell must resist separation. Lateral wind produces arch-like stress patterns oriented against the applied force."] },
      { type: "mediaGroup", groups: ["principalstress", "study1results"], fallbackGroups: ["stress"], layout: "asymmetric", label: "PRINCIPAL STRESSES", placeholderCount: 3 },
      { type: "sectionTitle", number: "09", title: "Force Flow: Study 01" },
      { type: "text", heading: "Demand migrating toward supports", paragraphs: ["Force-flow diagrams show how structural demand travels from central shell regions toward the supports and how that pattern changes with wind direction."] },
      { type: "mediaGroup", groups: ["forceflow", "study1results"], fallbackGroups: ["analysis"], layout: "full", label: "FORCE FLOW", placeholderCount: 1 },
      { type: "sectionTitle", number: "10", title: "Study 02: Symmetric vs Asymmetric" },
      { type: "text", heading: "A strong formal study with structural limits", paragraphs: ["Variation 04 is preferred within the asymmetric family. Under gravity, however, its utilisation exceeds the acceptable range and the geometry is not considered construction-suitable in the documented evaluation."] },
      { type: "mediaGroup", groups: ["study2", "asymmetric"], fallbackGroups: ["analysis"], layout: "gallery", label: "STUDY 02", placeholderCount: 4 },
      { type: "sectionTitle", number: "11", title: "Study 03: Three-Legged Structures" },
      { type: "text", heading: "Testing reduced support", paragraphs: ["The three-legged family investigates a more uneven support topology. The resulting force flow and local demand reveal issues that make the system less convincing than the clearest four-legged alternative."] },
      { type: "mediaGroup", groups: ["study3", "threelegged"], fallbackGroups: ["analysis"], layout: "gallery", label: "STUDY 03", placeholderCount: 4 },
      { type: "sectionTitle", number: "12", title: "Overall Conclusion" },
      { type: "text", heading: "Variation 01", paragraphs: ["Variation 01 from the symmetric study remains the clearest overall direction because it offers the strongest combined reading of geometry, support logic and documented performance."] },
      { type: "mediaGroup", groups: ["preferred", "final"], fallbackGroups: ["result"], layout: "asymmetric", label: "PREFERRED DIRECTION", placeholderCount: 3 },
      { type: "sectionTitle", number: "13", title: "Project Narrative" },
      { type: "flow", label: "Structural research sequence", steps: ["Bridge design space", "3-leg / 4-leg variants", "Symmetry / asymmetry", "Kangaroo form finding", "Karamba analysis", "Compare metrics", "Extract structural learning", "Select geometric logic"] },
      { type: "mediaGroup", groups: ["comparison", "catalogue"], fallbackGroups: ["analysis"], layout: "full", label: "STRUCTURAL CATALOGUE", placeholderCount: 1 },
    ],
  },
  {
    id: "origami-tree",
    number: "13",
    slug: "origami-tree",
    title: "Origami Tree",
    subtitle: "Computational art and fabrication",
    year: null,
    type: "Professional Work",
    projectType: "Computational Art",
    classification: "Professional",
    office: "Hexagramm Design Pvt. Ltd.",
    principalArchitect: "Ar. Ankon Mitra",
    collaborators: ["Naitik Sharma"],
    role: "Computational development and fabrication documentation",
    location: "India Art Fair",
    context: "India Art Fair",
    keywords: ["Computational Design", "Origami", "Fabrication", "Panelisation", "Nesting"],
    tags: ["Professional", "Parametric Design", "Fabrication", "Computational Art"],
    indexFocus: "Computational Fabrication / Origami",
    shortDescription: "A computational workflow translating branching curves into triangulated, folded and fabrication-ready tree components.",
    introduction: ["Origami Tree translates a branching curve network into a triangulated folded surface assembled from labelled, fabrication-ready strips.", "The workflow connects geometric development, component variation, sheet nesting, nomenclature and an internal metal support to the final built installation at India Art Fair."],
    externalLinks: [],
    mediaFolder: "/projects/origami-tree",
    thumbnail: null,
    thumbnailType: "image",
    thumbnailAlt: "Origami Tree computational art installation",
    heroMedia: null,
    heroMediaType: "image",
    heroAlt: "Built Origami Tree installation at India Art Fair",
    featured: false,
    archive: true,
    placeholder: false,
    visualVariant: "folded",
    content: [
      { type: "sectionTitle", number: "01", title: "Parametric Tree Input" },
      { type: "text", heading: "Trunk and branch curves", paragraphs: ["A small set of curves representing the tree trunk and branches forms the input to a reusable Grasshopper workflow capable of processing multiple tree geometries."] },
      { type: "mediaGroup", groups: ["input", "curves", "grasshopper"], fallbackGroups: ["process"], layout: "asymmetric", label: "PARAMETRIC INPUT", placeholderCount: 3 },
      { type: "sectionTitle", number: "02", title: "Mesh Generation" },
      { type: "text", heading: "Curves to a volumetric tree", paragraphs: ["The input curves are transformed into a continuous mesh describing the trunk and branches. Plan and elevation views make this first geometric translation legible."] },
      { type: "flow", label: "Initial translation", steps: ["Curves", "Volumetric tree", "Mesh"] },
      { type: "mediaGroup", groups: ["mesh", "geometry"], fallbackGroups: ["process"], layout: "two-column", label: "MESH GENERATION", placeholderCount: 2 },
      { type: "sectionTitle", number: "03", title: "Mesh Triangulation" },
      { type: "text", heading: "Organic branching as flat facets", paragraphs: ["The continuous mesh is triangulated so the curved organic form can be fabricated from sheet material as a collection of planar faces."] },
      { type: "mediaGroup", groups: ["triangulation"], fallbackGroups: ["mesh"], layout: "asymmetric", label: "MESH TRIANGULATION", placeholderCount: 3 },
      { type: "sectionTitle", number: "04", title: "Surface Articulation" },
      { type: "text", heading: "Pyramids on selected faces", paragraphs: ["Selected triangulated faces are manipulated into pyramid-like projections, creating depth and the articulated origami character of the final skin."] },
      { type: "mediaGroup", groups: ["pyramid", "articulation"], fallbackGroups: ["process"], layout: "gallery", label: "SURFACE ARTICULATION", placeholderCount: 4 },
      { type: "sectionTitle", number: "05", title: "Mesh Strip Generation" },
      { type: "text", heading: "Rationalising the skin for fabrication", paragraphs: ["Connected facets are organised into fabrication strips. The workflow is rationalised toward reducing strip count, cost and material waste without claiming an undocumented formal optimisation algorithm."] },
      { type: "mediaGroup", groups: ["strip", "unroll"], fallbackGroups: ["fabrication"], layout: "gallery", label: "MESH STRIPS", placeholderCount: 4 },
      { type: "sectionTitle", number: "06", title: "Segmentation for Transportation" },
      { type: "text", heading: "Dividing branches into buildable sections", paragraphs: ["The complete tree could not be fabricated or transported as one object. Coloured branch sections make fabrication, handling, transportation and site installation manageable."] },
      { type: "mediaGroup", groups: ["segmentation", "transport"], fallbackGroups: ["diagram"], layout: "asymmetric", label: "TRANSPORT SEGMENTATION", placeholderCount: 3 },
      { type: "sectionTitle", number: "07", title: "Nomenclature" },
      { type: "text", heading: "Keeping components traceable", paragraphs: ["Labels A-G connect digital geometry, fabrication information and installation position across the segmented assemblies."] },
      { type: "dataGrid", label: "Assembly labels", items: ["A", "B", "C", "D", "E", "F", "G"] },
      { type: "mediaGroup", groups: ["nomenclature"], fallbackGroups: ["segmentation"], layout: "gallery", label: "A-G NOMENCLATURE", placeholderCount: 4 },
      { type: "sectionTitle", number: "08", title: "Four Tree Variants" },
      { type: "text", heading: "A compact component catalogue", paragraphs: ["Four primary trees have different branching geometries and component quantities. They are presented together before the page moves into detailed fabrication."] },
      { type: "dataGrid", label: "Documented trees", items: ["T1", "T2", "T3", "T4"] },
      { type: "mediaGroup", groups: ["variant", "trees"], fallbackGroups: ["catalogue"], layout: "gallery", label: "T1-T4", placeholderCount: 4 },
      { type: "sectionTitle", number: "09", title: "Fabrication Workflow" },
      { type: "flow", label: "Model-to-fabrication sequence", steps: ["Input curves", "Generate mesh", "Triangulate", "Create pyramids", "Generate strips", "Segment mesh", "Nomenclature", "Visualise", "Bounding box", "Nest", "Fabricate"] },
      { type: "mediaGroup", groups: ["workflow", "animation"], fallbackGroups: ["grasshopper", "process"], layout: "asymmetric", label: "FABRICATION WORKFLOW / GIF", placeholderCount: 3 },
      { type: "sectionTitle", number: "10", title: "Nesting" },
      { type: "text", heading: "Preparing production sheets", paragraphs: ["The unfolded and labelled components were nested across approximately 310 A1 sheets, connecting the geometric model directly to a large fabrication package."] },
      { type: "dataGrid", label: "Fabrication package", items: [{ label: "Sheets", value: "Approx. 310" }, { label: "Sheet size", value: "A1" }] },
      { type: "mediaGroup", groups: ["nesting", "sheets"], fallbackGroups: ["fabrication"], layout: "gallery", label: "SHEET NESTING", placeholderCount: 4 },
      { type: "sectionTitle", number: "11", title: "Internal Metal Structure" },
      { type: "text", heading: "Supporting the folded skin", paragraphs: ["An internal metal structure provides the primary support for the folded assembly and coordinates the branching form with buildable connections and installation sequencing."] },
      { type: "mediaGroup", groups: ["structure", "metal"], fallbackGroups: ["technical"], layout: "asymmetric", label: "INTERNAL METAL STRUCTURE", placeholderCount: 3 },
      { type: "sectionTitle", number: "12", title: "Built Installation" },
      { type: "text", heading: "India Art Fair", paragraphs: ["The final installation brings together the computational surface, rationalised component families, extensive sheet package, metal support and on-site assembly process."] },
      { type: "flow", label: "Built translation", steps: ["Curves", "Parametric model", "Triangulated mesh", "Segmentation", "Nesting", "Metal fabrication", "Assembly", "India Art Fair installation"] },
      { type: "mediaGroup", groups: ["final", "built"], fallbackGroups: ["result"], layout: "full", label: "BUILT ORIGAMI TREE", placeholderCount: 3 },
    ],
  },
];
