import { archiveProjects } from "./archiveProjects.js";
import { newProfessionalProjects } from "./newProfessionalProjects.js";

// Project content is kept in data files so case studies can be edited without
// changing the visual components.
// Media is discovered at build time from public/projects/<slug>/images and /gifs.

const currentProjects = [
  {
    id: "hilton-hotel-nepal",
    number: "01",
    slug: "hilton-hotel-nepal",
    title: "Hilton Hotel, Kathmandu",
    subtitle: "Facade rationalisation and computational fabrication",
    year: "2023-2024",
    location: "Kathmandu, Nepal",
    type: "Professional Work",
    projectType: "Hospitality",
    classification: "Professional",
    office: "Studio Symbiosis",
    officeLink: "https://studio-symbiosis.com/project/hilton-kathmandu/",
    architecturalProject: "Studio Symbiosis",
    role: "Computational Design / Facade Rationalisation / Shop Drawing Production / Fabrication Development",
    collaborators: ["Studio Symbiosis project team, including Naitik Sharma"],
    guides: [],
    technicalCredit: null,
    imageCredit: "Studio Symbiosis",
    keywords: ["Parametric", "Massing", "Facade Design", "Environmental Simulations"],
    tags: ["Parametric", "Facade Design", "Computational Design", "Digital Fabrication"],
    indexFocus: "Facade Rationalisation / Computational Fabrication",
    shortDescription: "Computational facade rationalisation, fabrication and shop-drawing workflow developed at Studio Symbiosis.",
    introduction: [
      "Hilton Hotel, Nepal uses expressive GFRC scissor bands integrated with a curtain-wall facade. My contribution focused on rationalising the curved band geometry and translating it into coordinated, transportable and installable components.",
      "The computational workflow connected the design geometry to shop drawings, CNC-cut mould frameworks, assembly information and construction. It did not treat fabrication as a separate downstream exercise; the constraints of segmentation, transport and continuity informed how the facade was resolved.",
      "Within the wider Studio Symbiosis team, my role included remodelling facade bands against site and cleat conditions, coordinating the geometry with the facade consultant, site team and mild-steel frame, and documenting components for review and fabrication. This was a technical delivery role within a collaborative project, not sole design authorship.",
    ],
    externalLinks: [{ label: "Studio Symbiosis — Hilton Kathmandu", url: "https://studio-symbiosis.com/project/hilton-kathmandu/", kind: "Official Project Page" }],
    mediaCredit: "Official project documentation — Studio Symbiosis",
    mediaFolder: "/projects/hilton-hotel-nepal",
    thumbnail: null,
    thumbnailType: "image",
    thumbnailAlt: "Hilton Hotel, Nepal facade project media",
    heroMedia: null,
    heroMediaType: "image",
    heroAlt: "Hilton Hotel, Nepal facade",
    featured: false,
    placeholder: false,
    visualVariant: "field",
    content: [
      { type: "sectionTitle", number: "01", title: "Form Development" },
      { type: "text", heading: "From massing to an expressive facade", paragraphs: ["The project developed through a sequence of massing and form studies before the facade bands were coordinated with the curtain-wall system. The web layout reserves a wide sequence for this evolution rather than reducing it to a single diagram."] },
      { type: "mediaGroup", groups: ["form"], fallbackGroups: ["process"], layout: "three-column", label: "FORM DEVELOPMENT", placeholderCount: 3, caption: "Form-development sequence." },
      { type: "sectionTitle", number: "02", title: "Facade System" },
      { type: "imageText", heading: "GFRC bands and curtain wall", paragraphs: ["The facade combines expressive GFRC scissor bands with mullions, cleats, brackets and MS-pipe substructure. The system had to preserve the continuous reading of the bands while remaining buildable as discrete parts."], image: { src: null, mediaGroup: "facade", alt: "Hilton facade system showing bands and supporting components", label: "FACADE SYSTEM" } },
      { type: "mediaGroup", groups: ["facade"], layout: "two-column", label: "FACADE DETAIL", placeholderCount: 2 },
      { type: "text", heading: "Site and cleat coordination", paragraphs: ["The facade bands were checked and remodelled where required against site measurements, cleat positions and the mild-steel support frame. The work involved coordination with the facade consultant and site team, shop-drawing production, fabrication review and site or facility visits where required."] },
      { type: "dataGrid", label: "Role boundaries", items: ["Band remodelling", "Site-condition cross-checks", "Cleat + MS-frame coordination", "Shop drawings", "Fabrication review", "Team-based delivery"] },
      { type: "sectionTitle", number: "03", title: "Computational Rationalisation" },
      { type: "text", heading: "Perpendicular sections as fabrication geometry", paragraphs: ["Multiple perpendicular section planes were distributed along the curved surface to segment the scissor bands into components that could be transported and installed.", "The section curves also became guiding geometry for accurate shop drawings. By using the same geometric logic for adjacent components, the workflow helped maintain continuity between neighbouring pieces."] },
      { type: "mediaGroup", groups: ["rationalisation", "segmentation"], fallbackGroups: ["diagram"], layout: "asymmetric", label: "CUTTING PLANES / SEGMENTATION", placeholderCount: 3, caption: "Cutting planes, section curves, numbered components and assembly geometry." },
      { type: "sectionTitle", number: "04", title: "From Geometry to Fabrication" },
      { type: "textImage", heading: "Manageable and traceable components", paragraphs: ["The entrance lobby and ADD bands included cantilevering components extending more than three metres. To make them manageable during construction, the bands were subdivided into smaller pieces.", "Each piece was uniquely labelled and issued with assembly and isometric drawings, allowing the digital segmentation model to remain legible through fabrication and installation."], image: { src: null, mediaGroup: "fabrication", alt: "Hilton component labelling and assembly drawing", label: "SHOP DRAWING / ASSEMBLY" } },
      { type: "sectionTitle", number: "05", title: "CNC + Mould Workflow" },
      { type: "flow", label: "Fabrication sequence", steps: ["Sectioning", "8' x 4' MDF nesting", "CNC cutting", "Interlocking framework", "GRC / FRP mould", "GFRC component"] },
      { type: "text", heading: "Sectioned mould frameworks", paragraphs: ["The band geometry was sectioned in two directions at approximately 150 mm spacing. The profiles were nested on 8' x 4' MDF sheets of approximately 8 mm thickness and prepared for CNC fabrication.", "Interlocking grooves allowed the cut profiles to assemble into frameworks for GRC and FRP mould preparation. Where typical-floor geometry allowed, moulds could be reused."] },
      { type: "mediaGroup", groups: ["cnc", "mould"], fallbackGroups: ["technical"], layout: "gallery", label: "CNC + MOULD WORKFLOW", placeholderCount: 4 },
      { type: "sectionTitle", number: "06", title: "Construction" },
      { type: "text", heading: "Digital continuity through construction", paragraphs: ["The final chapter follows the system from mould assembly and GFRC production to steel substructure, site installation and the finished bands."] },
      { type: "flow", label: "Project sequence", steps: ["Architectural form", "Complex facade bands", "Site / cleat coordination", "Parametric remodelling", "Band typologies", "Perpendicular sectioning", "Component subdivision", "Nomenclature", "Shop drawings", "8' x 4' MDF nesting", "CNC fabrication", "Interlocking rib framework", "GRC / FRP mould", "GFRC production", "Site installation"] },
      { type: "mediaGroup", groups: ["construction", "final"], fallbackGroups: ["fabrication", "result"], layout: "asymmetric", label: "CONSTRUCTION / BUILT FACADE", placeholderCount: 3 },
    ],
  },
  {
    id: "circular-hub",
    number: "02",
    slug: "circular-hub",
    title: "Circular Hub",
    subtitle: "Reclaimed timber as computational input",
    year: "2026 — Ongoing",
    location: null,
    type: "Academic Work",
    projectType: "Research Project",
    classification: "Academic",
    institution: "CITA — Royal Danish Academy",
    role: null,
    collaborators: ["Naitik", "Lauren", "Irina"],
    guides: ["Paul Nicholas", "Gabriella Rossi"],
    technicalCredit: null,
    keywords: ["Parametric", "Circular Material", "Assembly"],
    tags: ["Research", "Parametric", "Circular Construction", "Material Systems", "Digital Fabrication"],
    indexFocus: "Circular Material / Computational Assembly",
    shortDescription: "A computational design system for reclaimed timber, reversible aggregation and graph-based disassembly intelligence.",
    introduction: [
      "Construction contributes 40% of global emissions and generates significant waste. Reusing salvaged timber offers an alternative, but reclaimed members cannot be treated as standardised stock because their geometries and performance are uncertain.",
      "Circular Hub investigates how reclaimed timber can instead become the input to a computational design system. Material characterisation, combinatorial connection rules, structural stress fields and graph representations are connected into a reversible assembly workflow.",
    ],
    externalLinks: [{ label: "Circular Hub — Aggregation Study", url: "https://www.instagram.com/p/DZTlGWjCGg5/", kind: "View Post" }],
    mediaFolder: "/projects/circular-hub",
    excludeFromHeroGroups: ["aggregation-visual-study"],
    thumbnail: null,
    thumbnailType: "image",
    thumbnailAlt: "Circular Hub reclaimed timber aggregation",
    heroMedia: null,
    heroMediaType: "image",
    heroAlt: "Circular Hub computational timber assembly",
    featured: false,
    placeholder: false,
    visualVariant: "assembly",
    content: [
      { type: "researchQuestion", text: "How can structural stress fields guide the aggregation of reclaimed timber into reversible assemblies, and how can graph-based representations enable disassembly intelligence?" },
      { type: "sectionTitle", number: "01", title: "Computational Pipeline" },
      { type: "flow", label: "Research pipeline", steps: ["Material Passport", "Combinatorial Construction Kit", "Structural Performative Design", "Material Allocation", "Graph Disassembly", "AR Assembly"] },
      { type: "mediaGroup", groups: ["pipeline"], fallbackGroups: ["diagram"], layout: "full", label: "COMPUTATIONAL PIPELINE", placeholderCount: 1 },
      { type: "sectionTitle", number: "02", title: "Material Passport" },
      { type: "text", heading: "Characterising irregular timber", paragraphs: ["The material passport extracts geometric features from salvaged members and uses them to organise irregular timber into families. Clustering and proxy geometry make the stock computationally accessible without erasing its differences."] },
      { type: "dataGrid", label: "Extracted features", items: ["Effective Length", "Tapering", "Straightness", "Longitudinal Area", "Oriented Bounding Box", "Compactness"] },
      { type: "flow", label: "Characterisation", steps: ["Feature Extraction", "Clustering / K-Means", "Timber Families", "Proxy Geometry", "Timber Grade"] },
      { type: "mediaGroup", groups: ["passport", "clustering"], fallbackGroups: ["diagram"], layout: "asymmetric", label: "MATERIAL PASSPORT", placeholderCount: 3 },
      { type: "sectionTitle", number: "03", title: "Connection System" },
      { type: "text", heading: "Reversible connection rules", paragraphs: ["A construction kit defines horizontal, rotational, 90-degree, vertical and combined connections. Dovetail grooves, dovetail keys and a split butterfly wedge joint translate the rule system into a reversible physical assembly logic."] },
      { type: "dataGrid", label: "Connection catalogue", items: ["Horizontal Connection", "Rotational Connection", "90 Degree Connection", "Vertical Connection", "Combined Connections"] },
      { type: "dataGrid", label: "Documented fabrication data", items: [{ label: "Process", value: "Robotic milling" }, { label: "Manufacturing time / joint", value: "2 min 45 sec" }, { label: "Sawdust / joint", value: "28 g" }, { label: "Barn beam average", value: "Approx. 30 x 30 cm" }] },
      { type: "mediaGroup", groups: ["connection", "joint"], fallbackGroups: ["technical", "fabrication"], layout: "gallery", label: "CONNECTION SYSTEM", placeholderCount: 4 },
      { type: "sectionTitle", number: "04", title: "Aggregation Rules" },
      { type: "text", heading: "A combinatorial construction kit", paragraphs: ["Parts A, B, C and D interact through predefined connection possibilities. The parts and their permitted relationships provide the combinatorial grammar from which larger assemblies can grow."] },
      { type: "dataGrid", label: "Part catalogue", items: ["Part A", "Part B", "Part C", "Part D"] },
      { type: "mediaGroup", groups: ["aggregation", "parts"], fallbackGroups: ["process"], layout: "three-column", label: "AGGREGATION RULES", placeholderCount: 3 },
      { type: "sectionTitle", number: "05", title: "Fields + Structural Influence" },
      { type: "imageText", heading: "Growth informed by fields", paragraphs: ["Vector fields influence rule selection and aggregation growth. Structural stress fields therefore participate in how the reclaimed members are allocated and how slab-scale assemblies develop."], image: { src: null, mediaGroup: "field", alt: "Vector field influencing reclaimed timber aggregation", label: "FIELD VISUALISATION / GIF" } },
      { type: "mediaGroup", groups: ["field", "animation"], fallbackGroups: ["gifs"], layout: "gallery", label: "FIELD + AGGREGATION", placeholderCount: 2 },
      { type: "sectionTitle", number: "06", title: "Architectural Application" },
      { type: "text", heading: "Material storage as spatial system", paragraphs: ["The architectural studies position timber storage and aggregation as part of the interior and its spatial organisation. The rendered application is one outcome of the material-computational system, rather than the project’s sole result."] },
      { type: "mediaGroup", groups: ["application", "final"], fallbackGroups: ["result"], layout: "asymmetric", label: "ARCHITECTURAL APPLICATION", placeholderCount: 3 },
      { type: "sectionTitle", number: "07", title: "Aggregation Studies" },
      { type: "text", heading: "Computational geometry and visual exploration", paragraphs: ["Alongside the formal reclaimed-timber research, aggregation studies were used as a testing ground for visual representation. The underlying computational assembly logic was retained while alternative AI-assisted visual languages were explored.", "The computational aggregation geometry belongs to the project logic; the cyberpunk or futuristic material appearance is a visualisation experiment and is not presented as the material proposal for the reclaimed-timber system."] },
      { type: "mediaGroup", groups: ["aggregation-visual-study"], fallbackGroups: ["aggregation"], layout: "full", label: "AGGREGATION VISUAL STUDY", placeholderCount: 1 },
    ],
  },
  {
    id: "arwad-tower-jeddah",
    number: "03",
    slug: "arwad-tower-jeddah",
    title: "Arwad Tower, Jeddah",
    subtitle: "Parametric massing and environmental facade development",
    year: "2023-2024",
    location: "Jeddah",
    type: "Professional Work",
    projectType: "Commercial Office",
    classification: "Professional",
    office: "Studio Symbiosis",
    architecturalProject: "Studio Symbiosis",
    role: null,
    collaborators: ["Amit Gupta", "Britta Knobbel", "Fulvio Wirz", "Manuele Gaino", "Naitik"],
    guides: [],
    technicalCredit: null,
    keywords: ["Parametric", "Massing", "Facade Design", "Environmental Simulations"],
    tags: ["Parametric", "Architecture", "Environmental Design", "Facade Design", "Computational Design"],
    indexFocus: "Parametric Massing / Environmental Facade",
    shortDescription: "Parametric massing, daylight and radiation studies connecting tower form with a phyllotaxis-based shading facade.",
    introduction: ["Arwad Tower is a commercial office development near Jeddah Airport combining flexible office floors, commercial spaces, parking, a full-height atrium, open terraces and informal meeting areas.", "Summer working-hour temperatures exceed approximately 45°C. This environmental constraint connected the massing study to daylight, radiation, shading and facade geometry rather than treating the envelope as a separate visual layer."],
    externalLinks: [],
    mediaFolder: "/projects/arwad-tower-jeddah",
    thumbnail: null,
    thumbnailType: "image",
    thumbnailAlt: "Arwad Tower, Jeddah project media",
    heroMedia: null,
    heroMediaType: "image",
    heroAlt: "Arwad Tower commercial office development",
    featured: false,
    placeholder: false,
    visualVariant: "matrix",
    content: [
      { type: "sectionTitle", number: "01", title: "Massing Catalogue" },
      { type: "text", heading: "A parametric option space", paragraphs: ["A catalogue was developed by varying core placement, commercial-space distribution, parking layouts, tower form and atrium configuration. Each alternative was evaluated through built-up area and daylight performance.", "The catalogue is intended to be read as a large comparison matrix, keeping the relationship between geometry and evaluation visible."] },
      { type: "dataGrid", label: "Catalogue variables", items: ["Core placement", "Commercial-space distribution", "Parking layouts", "Tower form", "Atrium configuration"] },
      { type: "dataGrid", label: "Evaluation", items: ["Built-Up Area / BUA", "Daylight"] },
      { type: "mediaGroup", groups: ["catalogue", "massing"], fallbackGroups: ["process"], layout: "gallery", label: "MASSING CATALOGUE", placeholderCount: 4 },
      { type: "sectionTitle", number: "02", title: "Option Selection" },
      { type: "imageText", heading: "Option 1", paragraphs: ["Option 1 was selected because it achieved high built-up area while maintaining daylight penetration through the atrium. Maximum ground coverage, urban alignments, stepped setbacks, the core and office zones were coordinated within this configuration."], image: { src: null, mediaGroup: "option", alt: "Selected Arwad Tower option showing atrium, core and office zones", label: "OPTION 1 / SELECTED" } },
      { type: "mediaGroup", groups: ["option"], fallbackGroups: ["diagram"], layout: "two-column", label: "OPTION SELECTION", placeholderCount: 2 },
      { type: "sectionTitle", number: "03", title: "Environmental Analysis" },
      { type: "text", heading: "Seasonal radiation study", paragraphs: ["Radiation was studied at the east, north, west and south corners across 21 June, 21 March, 23 September and 22 December. These comparisons informed where facade elements required orientation, overhang or vertical shading responses."] },
      { type: "dataGrid", label: "Facade locations", items: ["East Corner", "North Corner", "West Corner", "South Corner"] },
      { type: "dataGrid", label: "Study dates", items: ["21 June", "21 March", "23 September", "22 December"] },
      { type: "mediaGroup", groups: ["radiation", "environmental"], fallbackGroups: ["diagram"], layout: "gallery", label: "RADIATION ANALYSIS", placeholderCount: 4, caption: "Add source legends and units with the final radiation graphics." },
      { type: "sectionTitle", number: "04", title: "Facade Concept" },
      { type: "textImage", heading: "Phyllotaxis and self-shading", paragraphs: ["The facade concept draws from phyllotaxis. Overlapping and angled elements cast shadows onto neighbouring surfaces, reducing direct solar exposure through their geometric relationship.", "Element orientation, vertical louvers and overhangs respond to exposure while retaining a consistent facade system. No numerical energy saving is claimed by the source material."], image: { src: null, mediaGroup: "facade", alt: "Phyllotaxis-inspired facade shading geometry", label: "FACADE CONCEPT" } },
      { type: "mediaGroup", groups: ["facade", "shading"], fallbackGroups: ["technical"], layout: "asymmetric", label: "FACADE / SELF-SHADING", placeholderCount: 3 },
      { type: "sectionTitle", number: "05", title: "Form Development" },
      { type: "flow", label: "Architectural sequence", steps: ["Site", "Podium", "Office tower", "Central recesses / open spaces", "View-oriented configuration", "Facade / shading system"] },
      { type: "mediaGroup", groups: ["form"], fallbackGroups: ["process"], layout: "three-column", label: "FORM DEVELOPMENT", placeholderCount: 3 },
      { type: "sectionTitle", number: "06", title: "Final Architecture" },
      { type: "mediaGroup", groups: ["final"], fallbackGroups: ["result", "hero"], layout: "asymmetric", label: "FINAL ARCHITECTURE", placeholderCount: 3 },
    ],
  },
  {
    id: "biopol-3d-printing",
    number: "04",
    slug: "biopol-3d-printing",
    title: "BioPol 3D Printing",
    subtitle: "Fabrication-informed robotic toolpath planning",
    year: "2026",
    location: null,
    type: "Academic Work",
    classification: "Academic",
    projectType: "Research Project",
    institution: "CITA — Royal Danish Academy",
    role: null,
    collaborators: ["Naitik", "Gabrielle", "Filip", "Luis"],
    guides: ["Carl Eppinger", "Carly"],
    technicalCredit: null,
    keywords: ["Parametric", "Machine Learning", "Circular Material", "3D Printing", "Robotic Toolpath Planning"],
    tags: ["Parametric", "Machine Learning", "Circular Construction", "Robotic Fabrication", "Digital Fabrication"],
    indexFocus: "Machine Learning / Robotic 3D Printing",
    shortDescription: "A fabrication-informed workflow connecting bio-based material behaviour, geometry, adaptive toolpaths and robotic 3D printing.",
    introduction: ["BioPol 3D Printing investigates robotic extrusion with bio-based materials through a fabrication-informed computational design workflow. Geometry, material behaviour, toolpath generation, robotic fabrication and machine learning are treated as an interdependent system.", "The study works through print velocity, material flow, density, pressure, collapse thresholds, overhang, infill geometry and non-planar slicing to understand how an arch prototype can be rationalised and printed."],
    externalLinks: [],
    mediaFolder: "/projects/biopol-3d-printing",
    thumbnail: null,
    thumbnailType: "image",
    thumbnailAlt: "BioPol robotic 3D printing project media",
    heroMedia: null,
    heroMediaType: "image",
    heroAlt: "Bio-based material robotic printing prototype",
    featured: false,
    placeholder: false,
    visualVariant: "topology",
    content: [
      { type: "sectionTitle", number: "01", title: "Fabrication Parameters" },
      { type: "text", heading: "Parameters that shape printability", paragraphs: ["The initial studies isolate parameters that influence deposition and stability. These variables form the shared language between geometric design, material tests and robotic toolpath planning."] },
      { type: "dataGrid", label: "Print variables", items: ["Overhang", "Infill Geometry", "Non-Planar Slicing", "Smooth vs Rough", "Print Speed", "Material Flow", "Material Density", "Pressure"] },
      { type: "mediaGroup", groups: ["parameter", "test", "animation"], fallbackGroups: ["process", "gifs"], layout: "gallery", label: "FABRICATION PARAMETERS / GIF", placeholderCount: 4 },
      { type: "sectionTitle", number: "02", title: "Form Development" },
      { type: "text", heading: "Arch prototype", paragraphs: ["The prototype developed through a controlled form sequence in which print constraints and material behaviour could be considered alongside the architectural geometry."] },
      { type: "mediaGroup", groups: ["form"], fallbackGroups: ["process"], layout: "three-column", label: "ARCH FORM DEVELOPMENT", placeholderCount: 3 },
      { type: "sectionTitle", number: "03", title: "Component Rationalisation" },
      { type: "imageText", heading: "Variable brick components", paragraphs: ["The arch was rationalised into individual printed brick components with documented dimensional variation. The component drawing should remain large enough to read as technical information rather than decorative texture."], image: { src: null, mediaGroup: "component", alt: "BioPol brick component dimensions and variation", label: "COMPONENT DRAWING" } },
      { type: "mediaGroup", groups: ["component"], fallbackGroups: ["technical"], layout: "full", label: "COMPONENT RATIONALISATION", placeholderCount: 1 },
      { type: "sectionTitle", number: "04", title: "Machine Learning for Print-Path Optimisation" },
      { type: "text", heading: "Task, material and fabrication constraints", paragraphs: ["The workflow establishes a parametric relationship between the task, material and fabrication constraints. Print parameters such as bed size and deposition strategy define geometric limitations.", "Material behaviour, including overhang tolerance and compression capacity, affects structural stability. Machine learning is positioned within this fabrication context rather than as an isolated prediction exercise."] },
      { type: "mediaGroup", groups: ["ml", "optimisation"], fallbackGroups: ["diagram"], layout: "asymmetric", label: "ML / PRINT-PATH OPTIMISATION", placeholderCount: 3 },
      { type: "sectionTitle", number: "05", title: "Material Zoning" },
      { type: "textImage", heading: "Deposition according to demand", paragraphs: ["Material is distributed according to demand, transitioning from heavier deposition in high-demand regions to lighter infill in non-critical regions. The intention is efficient material use while maintaining structural performance."], image: { src: null, mediaGroup: "zoning", alt: "Material zoning across a printed BioPol component", label: "MATERIAL ZONING" } },
      { type: "flow", label: "Material distribution", steps: ["High-demand region", "Heavier deposition", "Transition", "Lighter infill", "Non-critical region"] },
      { type: "sectionTitle", number: "06", title: "Adaptive Toolpaths" },
      { type: "text", heading: "Computational control", paragraphs: ["Geometry, material behaviour and fabrication logic are resolved together through computational control. Adaptive toolpaths respond to the limits documented by the printing studies."] },
      { type: "dataGrid", label: "Documented ranges", items: [{ label: "Print velocity", value: "19.3-50 mm/s" }, { label: "Collapse-effect assumption", value: "0-27 mm" }] },
      { type: "mediaGroup", groups: ["toolpath", "animation"], fallbackGroups: ["diagram", "gifs"], layout: "gallery", label: "ADAPTIVE TOOLPATH / GIF", placeholderCount: 2 },
      { type: "sectionTitle", number: "07", title: "Prototype / Fabrication" },
      { type: "flow", label: "Feedback loop", steps: ["Material", "Geometry", "Toolpath", "Robot", "Print result"] },
      { type: "mediaGroup", groups: ["fabrication", "prototype", "final"], fallbackGroups: ["result"], layout: "asymmetric", label: "ROBOTIC PRINTING / PROTOTYPE", placeholderCount: 3 },
    ],
  },
  {
    id: "configurable-topologies",
    number: "05",
    slug: "configurable-topologies",
    title: "Configurable Topologies",
    subtitle: "Architectural classification through graph machine learning",
    year: "2022",
    location: null,
    type: "Academic Work",
    projectType: "Master's Thesis",
    classification: "Academic",
    institution: "Institute for Advanced Architecture of Catalonia — IAAC",
    institutionLink: "https://www.iaacblog.com/programs/configurable-topologies/",
    programme: "Master in Advanced Computation for Architecture & Design — MaCAD",
    role: "Individual Master's Thesis / Author",
    collaborators: ["Naitik Sharma"],
    guides: ["Oana Taut"],
    technicalCredit: "Prof. Wassim Jabi",
    keywords: ["Parametric", "Graph Machine Learning"],
    tags: ["Research", "Parametric", "Graph Machine Learning", "Machine Learning", "Generative Design"],
    indexFocus: "Graph Machine Learning / Architectural Topology",
    cardLabel: "Master's Thesis",
    shortDescription: "A thesis exploring classification of three-dimensional building prototypes through topological relationships and Graph Convolutional Networks.",
    introduction: ["Configurable Topologies investigates a recommendation and classification system for three-dimensional building prototypes based on their topological relationships.", "The thesis combines parametric modelling, architectural typologies, graph representation, graph features and supervised graph machine learning. Controlled synthetic datasets make the topological rules explicit before the work considers future application to real architectural and BIM data."],
    externalLinks: [{ label: "IAAC — Configurable Topologies", url: "https://www.iaacblog.com/programs/configurable-topologies/", kind: "Official Thesis Project Page" }],
    mediaCredit: "Official project documentation — IAAC",
    mediaFolder: "/projects/configurable-topologies",
    thumbnail: null,
    thumbnailType: "image",
    thumbnailAlt: "Configurable Topologies graph machine learning thesis",
    heroMedia: null,
    heroMediaType: "image",
    heroAlt: "Architectural prototypes and graph representations",
    featured: true,
    placeholder: false,
    visualVariant: "topology",
    content: [
      { type: "sectionTitle", number: "01", title: "Research Workflow" },
      { type: "flow", label: "Conceptual workflow", steps: ["Architectural Precedents", "Parametric Synthetic Dataset", "Graph Encoding", "Node Features", "Graph Convolutional Network", "Typology Prediction"] },
      { type: "mediaGroup", groups: ["workflow"], fallbackGroups: ["diagram"], layout: "full", label: "RESEARCH WORKFLOW", placeholderCount: 1 },
      { type: "sectionTitle", number: "02", title: "Building Typologies" },
      { type: "typologyGrid", items: [{ number: "01", title: "Slab Building", description: "A long circulation corridor with rooms on both sides, together with ground, stilt and staircase relationships." }, { number: "02", title: "Perimeter Block", description: "A central courtyard connected to the ground." }, { number: "03", title: "High-Rise Building", description: "A central core connected to podium and ground, with flats connected to the core." }] },
      { type: "mediaGroup", groups: ["typology"], fallbackGroups: ["process"], layout: "three-column", label: "BUILDING TYPOLOGIES", placeholderCount: 3 },
      { type: "sectionTitle", number: "03", title: "Dataset Generation" },
      { type: "text", heading: "Controlled synthetic architectural data", paragraphs: ["Synthetic architectural datasets were generated parametrically in Grasshopper. The dataset is controlled through architectural relationships and should not be described simply as AI-generated buildings."] },
      { type: "mediaGroup", groups: ["dataset"], fallbackGroups: ["process"], layout: "gallery", label: "PARAMETRIC DATASET", placeholderCount: 4 },
      { type: "sectionTitle", number: "04", title: "Graph Encoding" },
      { type: "text", heading: "Encoding spaces and relationships", paragraphs: ["Building prototypes are represented through nodes and edges. Node features include one-hot encoding and closeness centrality, allowing the graph to retain both categorical identity and relational information."] },
      { type: "dataGrid", label: "Documented node categories", items: [{ label: "Staircase", value: "0" }, { label: "Column", value: "1" }, { label: "Room", value: "2" }, { label: "Corridor", value: "3" }, { label: "Ground", value: "4" }, { label: "Core", value: "5" }, { label: "Podium", value: "6" }] },
      { type: "mediaGroup", groups: ["graph", "encoding"], fallbackGroups: ["diagram"], layout: "asymmetric", label: "GRAPH ENCODING", placeholderCount: 3 },
      { type: "sectionTitle", number: "05", title: "Graph Machine Learning" },
      { type: "textImage", heading: "Supervised graph classification", paragraphs: ["Supervised graph learning using Graph Convolutional Networks was used to classify the building graphs. Training and validation graphs, network configuration, accuracy and loss are retained as distinct parts of the evaluation."], image: { src: null, mediaGroup: "training", alt: "Graph Convolutional Network training and validation diagrams", label: "GCN TRAINING" } },
      { type: "mediaGroup", groups: ["training", "network"], fallbackGroups: ["diagram"], layout: "gallery", label: "GRAPH MACHINE LEARNING", placeholderCount: 4 },
      { type: "sectionTitle", number: "06", title: "Training + Results" },
      { type: "text", heading: "Experiments kept in context", paragraphs: ["The source portfolio documents multiple experiments with different accuracy and loss results. Those results should remain associated with their individual experiment graphics rather than being combined into one metric."] },
      { type: "dataGrid", label: "Documented configuration", items: [{ label: "Dataset", value: "600 graphs" }, { label: "Learning rate", value: "0.002" }, { label: "Batch size", value: "1" }, { label: "Hidden layers", value: "16 / 32 / 32 / 16" }, { label: "Pooling", value: "avgPooling" }] },
      { type: "dataGrid", label: "Final dataset reported in the source", items: [{ label: "Training", value: "200 graphs per typology" }, { label: "Validation", value: "180 graphs per typology" }] },
      { type: "dataGrid", label: "Documented experiment results", items: [{ label: "Configuration test", value: "100% accuracy / 0.001 loss" }, { label: "Validation comparison", value: "2 wrong predictions out of 90 / 96% accuracy / 0.2 loss" }] },
      { type: "mediaGroup", groups: ["result", "accuracy", "loss"], fallbackGroups: ["diagram"], layout: "gallery", label: "TRAINING RESULTS", placeholderCount: 4 },
      { type: "sectionTitle", number: "07", title: "Future Development" },
      { type: "text", heading: "Beyond synthetic voxel graphs", paragraphs: ["Future research could move beyond simple synthetic voxel-based graphs and incorporate real architectural or BIM data. The documented extensions include real-world BIM datasets, homogeneous graphs and heterogeneous graphs."] },
      { type: "dataGrid", label: "Potential extensions", items: ["Real-world BIM datasets", "Homogeneous graphs", "Heterogeneous graphs"] },
      { type: "mediaGroup", groups: ["future", "final"], fallbackGroups: ["result"], layout: "full", label: "FUTURE DEVELOPMENT", placeholderCount: 1 },
    ],
  },
];

const projectOrder = [
  { slug: "hilton-hotel-nepal", category: "professional" },
  { slug: "arwad-tower-jeddah", category: "professional" },
  { slug: "the-crown-sector-111", category: "professional" },
  { slug: "the-edition-sector-66", category: "professional" },
  { slug: "the-dunes-udaipur", category: "professional" },
  { slug: "origami-tree", category: "professional" },
  { slug: "circular-hub", category: "academic" },
  { slug: "biopol-3d-printing", category: "academic" },
  { slug: "configurable-topologies", category: "academic" },
  { slug: "machine-learning-kerf-bending", category: "academic" },
  { slug: "post-digital-temples", category: "academic" },
  { slug: "charge-pavilion", category: "academic" },
  { slug: "above-and-inbetween", category: "academic" },
  { slug: "rhizome-space-habitat", category: "academic" },
  { slug: "environmental-studies-sydney", category: "academic" },
  { slug: "structural-studies-dharavi", category: "academic" },
];

const projectSources = [...currentProjects, ...archiveProjects, ...newProfessionalProjects];

export const projects = projectOrder.map(({ slug, category }, index) => {
  const project = projectSources.find((item) => item.slug === slug);
  if (!project) throw new Error(`Missing project data for ${slug}`);

  return {
    ...project,
    number: String(index + 1).padStart(2, "0"),
    category,
    archive: category === "academic",
    featured: project.featured === true,
  };
});

export function getProject(slug) {
  return projects.find((project) => project.slug === slug);
}
