export const resume = {
  introduction:
    "Architect and computational designer with experience spanning architectural practice, parametric workflows, environmental analysis, digital fabrication, BIM interoperability and computational research.",
  resumePdf: null,
  focus: [
    "Computational Design",
    "Digital Fabrication",
    "Circular Construction",
    "Material Systems",
    "Environmental Design",
    "Machine Learning",
    "Custom Digital Tools Development",
  ],
  experience: [
    {
      period: "2026—Current",
      role: "Computational Design Instructor",
      organisation: "Aerie Academy",
      location: "Online",
      description:
        "Teaching Basics of Computational Design, a three-month Rhino and Grasshopper course progressing from parametric modelling fundamentals to generative, optimisation-based and AI-assisted visualisation workflows.",
      link: "https://www.aerieacademy.com/courses/845694",
      linkLabel: "View course",
    },
    {
      period: "2022—2025",
      role: "Architect + Computational Designer",
      organisation: "Studio Symbiosis",
      location: "New Delhi, India",
      description:
        "Fabrication drawings, hospitality concept design, Rhino-to-Revit workflows using Rhino.Inside, environmental simulations and presentations, parametric façade development and Grasshopper-supported fabrication workflows.",
    },
    {
      period: "19 Oct 2020—12 Oct 2021",
      role: "Executive Architect",
      organisation: "Hexagramm Design Pvt. Ltd.",
      location: "India",
      description:
        "Architectural documentation, site coordination, BOQs, working drawings and visualisation alongside parametric product, installation and fabrication workflows.",
    },
    {
      period: "1 Aug 2019—29 Feb 2020",
      role: "Junior Architect",
      organisation: "Pulkit Soni Architects",
      location: "Jaipur, India",
      description: null,
    },
    {
      period: "1 May 2019—27 Jul 2019",
      role: "Junior Architect",
      organisation: "Ocube Architects",
      location: "Jaipur, India",
      description: null,
    },
    {
      period: "27 Feb 2019—27 Apr 2019",
      role: "Junior Architect",
      organisation: "rat[LAB] Studio",
      location: "New Delhi, India",
      description: null,
    },
    {
      period: "14 Jun 2018—1 Nov 2018",
      role: "Junior Architect",
      organisation: "Pulkit Soni Architects",
      location: "Jaipur, India",
      description: null,
    },
    {
      period: "1 Jul 2016—10 Jan 2017",
      role: "Intern Architect — Academic Internship",
      organisation: "Kshetra Architects",
      location: "New Delhi, India",
      description: null,
    },
  ],
  education: [
    {
      period: "2025—2027",
      qualification: "Master of Arts (M.A.) in Architecture",
      programme: "CITAstudio: Computation in Architecture",
      institution: "Royal Danish Academy — CITA",
      department: "Centre for Information Technology & Architecture",
      location: "Copenhagen, Denmark",
      focus: [
        "Computational Design",
        "Digital Fabrication",
        "Circular Construction",
        "Material Systems",
        "Environmental Design",
        "Machine Learning",
        "Custom Digital Tools Development",
      ],
    },
    {
      period: "2021—2022",
      qualification: "Master’s in Advanced Computation & Design (MaCAD)",
      programme: "Advanced Computation & Design",
      institution: "Institute for Advanced Architecture of Catalonia — IAAC",
      location: "Barcelona, Spain",
      focus: [
        "Parametric Modeling",
        "Environmental Design",
        "Structural Design",
        "BIM & Smart Construction",
        "Cloud-Based Data Management",
        "Machine Learning / Artificial Intelligence",
        "Advanced Computational Workflows",
      ],
    },
    {
      period: "2013—2018",
      qualification: "Bachelor’s in Architecture — B.Arch",
      programme: "Architecture",
      institution: "MBM Engineering College / JNVU University",
      location: "Jodhpur, Rajasthan, India",
      focus: [
        "Architectural Design",
        "Building Construction",
        "Structures",
        "Urban Design & Town Planning",
        "Building Services",
        "Architectural Conservation",
      ],
    },
  ],
  skills: [
    {
      category: "Computational Design",
      priority: "core",
      items: ["Rhino / Grasshopper", "GhPython / Python", "Parametric Modeling", "Algorithmic Design", "Optimisation Workflows", "Generative Workflows"],
    },
    {
      category: "Environmental + Structural",
      priority: "core",
      items: ["Ladybug / Honeybee", "Karamba3D", "Environmental Simulation", "Solar / Daylight Analysis", "Structural Simulation", "Life Cycle Assessment"],
    },
    {
      category: "Digital Fabrication + Materials",
      priority: "core",
      items: ["Fabrication Workflows", "Automation", "Circular Construction", "Material Reuse", "Material Systems", "Adaptive Construction Systems"],
    },
    {
      category: "BIM + Interoperability",
      priority: "supporting",
      items: ["Revit", "Rhino.Inside.Revit", "Rhino / Revit Interoperability", "Speckle Workflows", "AEC Data Interoperability", "Fabrication Drawings"],
    },
    {
      category: "AI + Data — Studied / Researched",
      priority: "supporting",
      items: ["Machine Learning", "Graph Machine Learning", "PyTorch / DGL", "TensorFlow / Keras", "Computer Vision Concepts", "Data Encoding / Feature Selection"],
    },
    {
      category: "Digital Tools + Web",
      priority: "secondary",
      items: ["HTML / CSS / JavaScript", "Three.js", "Rhino Compute", "Interactive Computational Applications", "Cloud-Based Workflows"],
    },
  ],
  languages: [
    { language: "Hindi", level: "Native" },
    { language: "English", level: "Fluent" },
    { language: "Danish", level: "Learning" },
    { language: "German", level: "Basic / limited knowledge" },
  ],
  showWorkshops: false,
  workshops: [
    { period: "September 2021", title: "Collaborative AI: Human + AI Form", event: "ACADIA 2021", tutors: ["Chien-Hua Huang"] },
    { period: "June 2021", title: "Bending — Active Bamboo Shell Structures", event: "Digital Futures 2021", tutors: ["Dr. Kristoff Crolla"] },
    { period: "December 2016", title: "How to Make Smart Design Decisions for Greener Buildings", event: "CEPT SWS School", tutors: ["Ar. Vinay Ghatti", "Ar. Autif Saeed"] },
  ],
};
