export const teaching = {
  id: "aerie-academy",
  organisation: "Aerie Academy",
  role: "Computational Design Instructor",
  period: "2026 — Current",
  course: "Basics of Computational Design",
  format: "3-Month Course",
  focus: ["Rhino", "Grasshopper", "Computational Design", "Parametric Design", "Generative Design", "Optimisation", "AI-Assisted Visualisation"],
  description: "Teaching a three-month computational design course centred on Rhino and Grasshopper, taking students from parametric modelling fundamentals toward generative, optimisation-based and contemporary visualisation workflows through lectures, exercises, troubleshooting and project development.",
  courseLink: "https://www.aerieacademy.com/courses/845694",
  profileLink: "https://www.instagram.com/synthedesign/",
  mediaCredit: "Public teaching documentation — @synthedesign",
  introduction: {
    label: "Course Introduction",
    title: "Basics of Computational Design",
    mediaGroup: "course-introduction",
    link: "https://www.instagram.com/p/DYzi3gNOsxS/",
    description: "Course launch and introduction to the three-month Rhino and Grasshopper teaching programme.",
  },
  workflows: [
    {
      number: "01",
      label: "Data Trees",
      title: "BIG Serpentine Pavilion Teaching Exercise",
      mediaGroup: "data-trees-serpentine",
      link: "https://www.instagram.com/p/DbRCljaiAt2/",
      description: "Using BIG's 2016 Serpentine Pavilion as a teaching exercise, the class explored Grasshopper data structures and data trees by organising, shifting and stacking repeated box modules into a controlled parametric system.",
    },
    {
      number: "02",
      label: "Grasshopper → AI Render",
      title: "Parametric Geometry to Visualisation",
      mediaGroup: "ai-render-grasshopper",
      link: "https://www.instagram.com/p/DcQ7BGPClgl/",
      description: "Translating parametrically generated Grasshopper geometry into an architectural visualisation while retaining the underlying design language. The design geometry is Rhino and Grasshopper; the visualisation is AI-assisted rendering.",
    },
    {
      number: "03",
      label: "Iteration + Failure",
      title: "Geometric Fidelity",
      mediaGroup: "ai-render-failure",
      link: "https://www.instagram.com/p/DcRLmMxKZgZ/",
      description: "Failed iterations were used to discuss where image generation distorts or loses the original parametric geometry, and how prompting, control and geometric fidelity affect the result.",
    },
    {
      number: "04",
      label: "Static Geometry → Motion",
      title: "AI-Assisted Motion Studies",
      mediaGroup: "ai-motion-tower",
      link: "https://www.instagram.com/p/DcUy3O5qSRc/",
      description: "Extending a static Rhino and Grasshopper scene into AI-assisted architectural imagery and motion studies.",
    },
  ],
};
