// Professional case studies added from verified Studio Symbiosis credits and
// the supplied Udaipur reference documentation. Personal roles are kept
// separate from the architectural-project credit.

export const newProfessionalProjects = [
  {
    id: "the-crown-sector-111",
    slug: "the-crown-sector-111",
    title: "The Crown",
    subtitle: "Sector 111, Gurugram",
    year: null,
    location: "Sector 111, Gurugram, India",
    type: "Professional Work",
    projectType: "Residential",
    classification: "Professional",
    office: "Studio Symbiosis",
    officeLink: "https://studio-symbiosis.com/project/the-crown-sector-111/",
    architecturalProject: "Studio Symbiosis",
    designLeads: ["Amit Gupta", "Britta Knobel Gupta"],
    role: "Facade Optimisation",
    status: "Under Construction",
    programme: "Residential / Amenities / Clubhouse / Sports / Swimming Pool",
    siteArea: "15.9 acres",
    builtUpArea: "438,545 sq.m",
    collaborators: [],
    keywords: ["Facade Optimisation", "Parametric Design", "Residential", "Curvature", "Repetition"],
    tags: ["Professional", "Parametric Design", "Facade"],
    indexFocus: "Facade Optimisation",
    cardLabel: null,
    shortDescription: "Facade optimisation for a Gurugram residential development with vertically repeated, petal-inspired elements and controlled curvature transitions.",
    introduction: [
      "The Crown is a large residential development in Sector 111, Gurugram, designed by Studio Symbiosis. Its tower identity is organised through vertically growing, petal-inspired facade elements that connect the lower pedestrian scale to the upper terraces.",
      "My documented contribution was facade optimisation. The case study therefore focuses on how repeated facade elements, changing curvature and local architectural conditions were translated into a controlled parametric system within the wider studio project.",
    ],
    externalLinks: [
      { label: "Studio Symbiosis — The Crown", url: "https://studio-symbiosis.com/project/the-crown-sector-111/", kind: "Official Project Page" },
    ],
    mediaCredit: "Official project documentation — Studio Symbiosis",
    mediaFolder: "/projects/the-crown-sector-111",
    thumbnail: null,
    thumbnailType: "image",
    thumbnailAlt: "The Crown residential towers and petal-inspired facade",
    heroMedia: null,
    heroMediaType: "image",
    heroAlt: "The Crown at Sector 111, Gurugram",
    featured: false,
    archive: false,
    placeholder: false,
    visualVariant: "field",
    content: [
      { type: "sectionTitle", number: "01", title: "Project Context" },
      { type: "text", heading: "Residential towers organised around landscape", paragraphs: ["The 15.9-acre development combines residences, amenities, clubhouse, sports and swimming facilities. The architectural project is credited to Studio Symbiosis; this page isolates the facade-optimisation contribution within that larger design."] },
      { type: "dataGrid", label: "Official project data", items: [{ label: "Status", value: "Under Construction" }, { label: "Site area", value: "15.9 acres" }, { label: "Built-up area", value: "438,545 sq.m" }, { label: "Programme", value: "Residential + amenities" }] },
      { type: "mediaGroup", groups: ["hero", "context"], fallbackGroups: ["overview"], layout: "asymmetric", label: "PROJECT CONTEXT", placeholderCount: 3 },
      { type: "sectionTitle", number: "02", title: "Facade Concept" },
      { type: "text", heading: "A vertical petal language", paragraphs: ["The facade language reinterprets petals as vertically growing elements that give the towers a continuous identity. Their curvature shifts at lower levels to respond to arrival, shade and pedestrian conditions."] },
      { type: "mediaGroup", groups: ["concept", "petal"], fallbackGroups: ["facade"], layout: "two-column", label: "FACADE CONCEPT", placeholderCount: 2 },
      { type: "sectionTitle", number: "03", title: "Facade Geometry" },
      { type: "text", heading: "A repeated architectural element", paragraphs: ["A common facade element establishes continuity across the tower while its control geometry accommodates changes in height, orientation and adjoining architectural conditions."] },
      { type: "mediaGroup", groups: ["geometry", "element"], fallbackGroups: ["process"], layout: "asymmetric", label: "FACADE GEOMETRY", placeholderCount: 3 },
      { type: "sectionTitle", number: "04", title: "Curvature Transitions" },
      { type: "text", heading: "Maintaining continuity through change", paragraphs: ["Curvature is treated as a transition rather than a set of disconnected profiles. The system controls how elements shift between typical vertical runs, lower-level bends and terrace conditions."] },
      { type: "mediaGroup", groups: ["curvature", "transition"], fallbackGroups: ["analysis"], layout: "gallery", label: "CURVATURE TRANSITIONS", placeholderCount: 4 },
      { type: "sectionTitle", number: "05", title: "Parameterisation" },
      { type: "flow", label: "Parametric control", steps: ["Facade reference", "Repeated element", "Local inputs", "Curvature control", "Transition check", "Coordinated output"] },
      { type: "mediaGroup", groups: ["parameter", "grasshopper"], fallbackGroups: ["workflow"], layout: "full", label: "PARAMETERISATION", placeholderCount: 1 },
      { type: "sectionTitle", number: "06", title: "Facade Optimisation" },
      { type: "text", heading: "Documented contribution", paragraphs: ["Facade Optimisation is the role credited to Naitik Sharma on the official project page. The work is presented as geometric rationalisation and coordination of the facade system; no undocumented objective function or performance metric is claimed."] },
      { type: "mediaGroup", groups: ["optimisation", "coordination"], fallbackGroups: ["technical"], layout: "asymmetric", label: "FACADE OPTIMISATION", placeholderCount: 3 },
      { type: "sectionTitle", number: "07", title: "Repetition vs Variation" },
      { type: "text", heading: "A family rather than one fixed component", paragraphs: ["The tower envelope balances the efficiency of repetition with the local variation required at corners, balconies, lower levels and terrace terminations."] },
      { type: "mediaGroup", groups: ["variation", "catalogue"], fallbackGroups: ["facade"], layout: "gallery", label: "ELEMENT FAMILY", placeholderCount: 4 },
      { type: "sectionTitle", number: "08", title: "Final Facade" },
      { type: "flow", label: "Facade sequence", steps: ["Petal language", "Repeated element", "Curvature variation", "Local conditions", "Parameterisation", "Facade optimisation", "Tower envelope"] },
      { type: "mediaGroup", groups: ["final"], fallbackGroups: ["hero", "result"], layout: "full", label: "FINAL FACADE", placeholderCount: 2 },
    ],
  },
  {
    id: "the-edition-sector-66",
    slug: "the-edition-sector-66",
    title: "The Edition",
    subtitle: "Sector 66, Gurugram",
    year: null,
    location: "Sector 66, Gurugram, India",
    type: "Professional Work",
    projectType: "Residential",
    classification: "Professional",
    office: "Studio Symbiosis",
    officeLink: "https://studio-symbiosis.com/project/the-edition-sector-66/",
    architecturalProject: "Studio Symbiosis",
    designLeads: ["Amit Gupta", "Britta Knobel Gupta"],
    role: "Facade Optimisation",
    status: "Under Construction",
    programme: "Residential / Amenities / Clubhouse / Sports / Swimming Pool",
    siteArea: "10.7 acres",
    builtUpArea: "364,990 sq.m",
    collaborators: [],
    keywords: ["Facade Optimisation", "Parametric Design", "Branching Geometry", "Balconies", "Residential"],
    tags: ["Professional", "Parametric Design", "Facade"],
    indexFocus: "Facade Optimisation",
    cardLabel: null,
    shortDescription: "Facade optimisation for a Gurugram residential development defined by a branching skeletal language and balcony-driven local variation.",
    introduction: [
      "The Edition is a residential development in Sector 66, Gurugram, designed by Studio Symbiosis. Three twin high-rise towers use a branching, skeletal facade language that grows across balconies and shifts vertically toward arrival and terrace conditions.",
      "My documented contribution was facade optimisation. This case study concentrates on parameterising the repeated system, coordinating it with balcony geometry and retaining architectural continuity through local variation.",
    ],
    externalLinks: [
      { label: "Studio Symbiosis — The Edition", url: "https://studio-symbiosis.com/project/the-edition-sector-66/", kind: "Official Project Page" },
    ],
    mediaCredit: "Official project documentation — Studio Symbiosis",
    mediaFolder: "/projects/the-edition-sector-66",
    thumbnail: null,
    thumbnailType: "image",
    thumbnailAlt: "The Edition twin towers and branching facade",
    heroMedia: null,
    heroMediaType: "image",
    heroAlt: "The Edition at Sector 66, Gurugram",
    featured: false,
    archive: false,
    placeholder: false,
    visualVariant: "assembly",
    content: [
      { type: "sectionTitle", number: "01", title: "Project Context" },
      { type: "text", heading: "Three twin towers and a shared landscape", paragraphs: ["The 10.7-acre residential development combines housing, amenities, clubhouse, sports and swimming facilities. Studio Symbiosis is credited for the architectural project; the case study focuses specifically on facade optimisation."] },
      { type: "dataGrid", label: "Official project data", items: [{ label: "Status", value: "Under Construction" }, { label: "Site area", value: "10.7 acres" }, { label: "Built-up area", value: "364,990 sq.m" }, { label: "Programme", value: "Residential + amenities" }] },
      { type: "mediaGroup", groups: ["hero", "context"], fallbackGroups: ["overview"], layout: "asymmetric", label: "PROJECT CONTEXT", placeholderCount: 3 },
      { type: "sectionTitle", number: "02", title: "Facade Language" },
      { type: "text", heading: "A branching skeletal system", paragraphs: ["The facade is conceived as a skeletal system that branches outward across the towers, producing a continuous vertical identity while responding to the residential floor plates."] },
      { type: "mediaGroup", groups: ["language", "facade"], fallbackGroups: ["concept"], layout: "two-column", label: "FACADE LANGUAGE", placeholderCount: 2 },
      { type: "sectionTitle", number: "03", title: "Branching Geometry" },
      { type: "text", heading: "From primary lines to local branches", paragraphs: ["Primary vertical elements establish the overall rhythm. Secondary branches negotiate balcony projections, perforations and the changing silhouette of the twin towers."] },
      { type: "mediaGroup", groups: ["branching", "geometry"], fallbackGroups: ["process"], layout: "asymmetric", label: "BRANCHING GEOMETRY", placeholderCount: 3 },
      { type: "sectionTitle", number: "04", title: "Balcony + Facade Relationships" },
      { type: "text", heading: "Coordinating architecture and envelope", paragraphs: ["Balcony edges and facade branches are treated as one coordinated condition. Local shifts maintain access, views, shade and visual continuity without forcing every floor into an identical facade profile."] },
      { type: "mediaGroup", groups: ["balcony", "coordination"], fallbackGroups: ["technical"], layout: "gallery", label: "BALCONY COORDINATION", placeholderCount: 4 },
      { type: "sectionTitle", number: "05", title: "Parameterisation" },
      { type: "flow", label: "Geometric workflow", steps: ["Tower reference", "Balcony edges", "Vertical skeleton", "Branch controls", "Local variation", "Coordinated facade"] },
      { type: "mediaGroup", groups: ["parameter", "grasshopper"], fallbackGroups: ["workflow"], layout: "full", label: "PARAMETERISATION", placeholderCount: 1 },
      { type: "sectionTitle", number: "06", title: "Facade Optimisation" },
      { type: "text", heading: "Documented contribution", paragraphs: ["Facade Optimisation is the role credited to Naitik Sharma on the official project page. The case study documents controlled geometric development and coordination without inventing optimisation metrics that are not present in the source."] },
      { type: "mediaGroup", groups: ["optimisation", "iteration"], fallbackGroups: ["analysis"], layout: "asymmetric", label: "FACADE OPTIMISATION", placeholderCount: 3 },
      { type: "sectionTitle", number: "07", title: "Repetition vs Local Variation" },
      { type: "text", heading: "Consistency across changing conditions", paragraphs: ["The facade retains a recognisable system while adjusting at balcony edges, tower junctions, lower levels and terrace bends. Repetition is used as a framework for local response rather than a fixed copy."] },
      { type: "mediaGroup", groups: ["variation", "catalogue"], fallbackGroups: ["facade"], layout: "gallery", label: "LOCAL VARIATION", placeholderCount: 4 },
      { type: "sectionTitle", number: "08", title: "Final Architecture" },
      { type: "flow", label: "Facade sequence", steps: ["Skeletal language", "Balcony relationships", "Branching geometry", "Parameterisation", "Local variation", "Facade optimisation", "Final envelope"] },
      { type: "mediaGroup", groups: ["final"], fallbackGroups: ["hero", "result"], layout: "full", label: "FINAL ENVELOPE", placeholderCount: 2 },
    ],
  },
  {
    id: "the-dunes-udaipur",
    slug: "the-dunes-udaipur",
    title: "The Dunes",
    subtitle: "Udaipur Resort",
    year: null,
    location: "Udaipur, Rajasthan, India",
    type: "Professional Work",
    projectType: "Hospitality",
    classification: "Professional",
    office: "Studio Symbiosis",
    architecturalProject: "Studio Symbiosis",
    role: "Computational Facade / Construction",
    status: null,
    programme: "Resort / Villas / Shared Amenities",
    collaborators: [],
    keywords: ["Computational Facade", "Grasshopper", "Curved Masonry", "Construction", "Rationalisation"],
    tags: ["Professional", "Parametric Design", "Facade", "Construction"],
    indexFocus: "Computational Facade / Construction",
    cardLabel: null,
    shortDescription: "Computational development and construction rationalisation for curved resort villas and a parametrically graded masonry facade in Udaipur.",
    introduction: [
      "The Dunes is a Studio Symbiosis resort project in Udaipur organised as a distributed field of villas within a desert landscape. Curved architectural geometry, local masonry and earthen finishes connect the digital model to regional construction.",
      "The available supplementary documentation records the shared project process: Rhino and Grasshopper geometry, rebar and wall coordination, a perforated facade gradient, a finite triangular component family, setting out and site construction. It is used here as project-process context and does not transfer another team member's individual responsibilities to Naitik.",
    ],
    externalLinks: [
      { label: "Grahesh Bhandari — Udaipur Resort documentation", url: "https://graheshbhandari.com/udaipur-resort", kind: "Supplementary Project Documentation" },
    ],
    mediaCredit: "Reference project documentation — Grahesh Bhandari",
    mediaFolder: "/projects/the-dunes-udaipur",
    thumbnail: null,
    thumbnailType: "image",
    thumbnailAlt: "The Dunes resort villas in Udaipur",
    heroMedia: null,
    heroMediaType: "image",
    heroAlt: "Curved villa geometry at The Dunes, Udaipur",
    featured: true,
    archive: false,
    placeholder: false,
    visualVariant: "terrain",
    content: [
      { type: "sectionTitle", number: "01", title: "Udaipur Context" },
      { type: "text", heading: "Architecture emerging from a desert landscape", paragraphs: ["The project uses a dispersed resort organisation and curved villa geometry to establish continuity between landscape, movement and built form. Local material and construction knowledge remain part of the computational-design problem."] },
      { type: "mediaGroup", groups: ["hero", "context"], fallbackGroups: ["overview"], layout: "asymmetric", label: "UDAIPUR CONTEXT", placeholderCount: 3 },
      { type: "sectionTitle", number: "02", title: "Distributed Villa Typology" },
      { type: "text", heading: "A field of individual curved villas", paragraphs: ["The resort is read as an aggregation of villa units rather than one monolithic building. Orientation, access, privacy and views establish the distributed site logic."] },
      { type: "mediaGroup", groups: ["masterplan", "villa"], fallbackGroups: ["site"], layout: "gallery", label: "VILLA TYPOLOGY", placeholderCount: 4 },
      { type: "sectionTitle", number: "03", title: "Curved Architectural Geometry" },
      { type: "text", heading: "Rhino and Grasshopper as coordination geometry", paragraphs: ["Curved villa surfaces are developed as controlled geometric references that can be interrogated for structural, masonry, facade and setting-out requirements."] },
      { type: "mediaGroup", groups: ["geometry", "grasshopper"], fallbackGroups: ["process"], layout: "asymmetric", label: "CURVED GEOMETRY", placeholderCount: 3 },
      { type: "sectionTitle", number: "04", title: "Structure + Rebar Coordination" },
      { type: "text", heading: "Translating freeform surfaces into construction information", paragraphs: ["The shared workflow coordinates curved form with structural and rebar information. Diagrams are retained as project-process evidence rather than attributed as another team member's personal role."] },
      { type: "mediaGroup", groups: ["rebar", "structure"], fallbackGroups: ["technical"], layout: "full", label: "REBAR COORDINATION", placeholderCount: 2 },
      { type: "sectionTitle", number: "05", title: "Curved Masonry" },
      { type: "text", heading: "Wall geometry, local brick and earthen finish", paragraphs: ["Curved wall conditions require a setting-out logic that can be understood by site teams and reconciled with local masonry construction and mud or earthen finishes."] },
      { type: "mediaGroup", groups: ["masonry", "wall"], fallbackGroups: ["construction"], layout: "asymmetric", label: "CURVED MASONRY", placeholderCount: 3 },
      { type: "sectionTitle", number: "06", title: "Perforated Facade Gradient" },
      { type: "text", heading: "Continuous appearance from a finite family", paragraphs: ["A parametric gradient controls perforation across the facade while a finite triangular tile or brick family rationalises the continuous digital field into repeatable construction components."] },
      { type: "flow", label: "Facade rationalisation", steps: ["Facade surface", "Gradient field", "Triangular subdivision", "Finite component family", "Nomenclature", "Setting out"] },
      { type: "mediaGroup", groups: ["facade", "gradient", "tile"], fallbackGroups: ["diagram"], layout: "gallery", label: "FACADE GRADIENT", placeholderCount: 4 },
      { type: "sectionTitle", number: "07", title: "Rationalisation + Setting Out" },
      { type: "text", heading: "Making digital variation traceable", paragraphs: ["Component limits, wall conditions and setting-out references translate the computational model into a construction sequence that can be checked on site."] },
      { type: "mediaGroup", groups: ["rationalisation", "settingout"], fallbackGroups: ["technical"], layout: "asymmetric", label: "SETTING OUT", placeholderCount: 3 },
      { type: "sectionTitle", number: "08", title: "Site Construction" },
      { type: "text", heading: "Digital-to-construction translation", paragraphs: ["Construction photographs close the case study by showing how curved geometry, structural coordination, masonry and perforated components are resolved through on-site fabrication and assembly."] },
      { type: "flow", label: "Project sequence", steps: ["Desert context", "Villa distribution", "Curved geometry", "Rebar coordination", "Masonry", "Facade gradient", "Rationalisation", "Setting out", "Construction"] },
      { type: "mediaGroup", groups: ["construction", "final"], fallbackGroups: ["result"], layout: "full", label: "SITE CONSTRUCTION", placeholderCount: 3 },
    ],
  },
];
